// This file was auto-generated by Fern from our API Definition.

import * as Payroc from "../../../src/api/index";
import { PayrocClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockBearer } from "../mockAuth";

describe("BankClient", () => {
    test("verify (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "1234001",
            bankAccount: {
                type: "pad",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "1234567890",
                transitNumber: "76543",
                institutionNumber: "543",
            },
        };
        const rawResponseBody = { processingTerminalId: "1234001", verified: true };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.paymentFeatures.bank.verify({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            processingTerminalId: "1234001",
            bankAccount: {
                type: "pad",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "1234567890",
                transitNumber: "76543",
                institutionNumber: "543",
            },
        });
        expect(response).toEqual({
            processingTerminalId: "1234001",
            verified: true,
        });
    });

    test("verify (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "1234001",
            bankAccount: {
                type: "ach",
                nameOnAccount: "Shara Hazel Hopper",
                accountNumber: "1234567890",
                routingNumber: "123456789",
            },
        };
        const rawResponseBody = { processingTerminalId: "1234001", verified: true };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.paymentFeatures.bank.verify({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            processingTerminalId: "1234001",
            bankAccount: {
                type: "ach",
                nameOnAccount: "Shara Hazel Hopper",
                accountNumber: "1234567890",
                routingNumber: "123456789",
            },
        });
        expect(response).toEqual({
            processingTerminalId: "1234001",
            verified: true,
        });
    });

    test("verify (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("verify (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("verify (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("verify (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("verify (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("verify (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("verify (9)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("verify (10)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            bankAccount: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-accounts/verify")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.paymentFeatures.bank.verify({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                bankAccount: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });
});
