// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
 *         serialNumber: "1850010868",
 *         operator: "Jane",
 *         processingTerminalId: "1234001",
 *         order: {
 *             orderId: "OrderRef6543",
 *             description: "Refund for order OrderRef6543",
 *             amount: 4999,
 *             currency: "USD"
 *         },
 *         customizationOptions: {
 *             entryMethod: "manualEntry"
 *         }
 *     }
 */
export interface RefundInstructionRequest {
    /** Serial number that identifies the merchant’s payment device. */
    serialNumber: string;
    /** Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency). */
    "Idempotency-Key": string;
    /** Operator who initiated the request. */
    operator?: string;
    /** Unique identifier that we assigned to the terminal. */
    processingTerminalId: string;
    order: Payroc.RefundInstructionOrder;
    customer?: Payroc.Customer;
    ipAddress?: Payroc.IpAddress;
    customizationOptions?: Payroc.CustomizationOptions;
}
