// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { FundingAccountsClient } from "../resources/fundingAccounts/client/Client.js";
import { FundingActivityClient } from "../resources/fundingActivity/client/Client.js";
import { FundingInstructionsClient } from "../resources/fundingInstructions/client/Client.js";
import { FundingRecipientsClient } from "../resources/fundingRecipients/client/Client.js";

export declare namespace FundingClient {
    export type Options = BaseClientOptions;
}

export class FundingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FundingClient.Options>;
    protected _fundingRecipients: FundingRecipientsClient | undefined;
    protected _fundingAccounts: FundingAccountsClient | undefined;
    protected _fundingInstructions: FundingInstructionsClient | undefined;
    protected _fundingActivity: FundingActivityClient | undefined;

    constructor(options: FundingClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get fundingRecipients(): FundingRecipientsClient {
        return (this._fundingRecipients ??= new FundingRecipientsClient(this._options));
    }

    public get fundingAccounts(): FundingAccountsClient {
        return (this._fundingAccounts ??= new FundingAccountsClient(this._options));
    }

    public get fundingInstructions(): FundingInstructionsClient {
        return (this._fundingInstructions ??= new FundingInstructionsClient(this._options));
    }

    public get fundingActivity(): FundingActivityClient {
        return (this._fundingActivity ??= new FundingActivityClient(this._options));
    }
}
