// This file was auto-generated by Fern from our API Definition.

export const ListPaymentLinksRequestChargeType = {
    Preset: "preset",
    Prompt: "prompt",
} as const;
export type ListPaymentLinksRequestChargeType =
    (typeof ListPaymentLinksRequestChargeType)[keyof typeof ListPaymentLinksRequestChargeType];
