// This file was auto-generated by Fern from our API Definition.

export const ListBankTransferRefundsRequestStatusItem = {
    Ready: "ready",
    Pending: "pending",
    Declined: "declined",
    Complete: "complete",
    Admin: "admin",
    Reversal: "reversal",
    Returned: "returned",
} as const;
export type ListBankTransferRefundsRequestStatusItem =
    (typeof ListBankTransferRefundsRequestStatusItem)[keyof typeof ListBankTransferRefundsRequestStatusItem];
