// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../index.js";

export interface ListDisputesSettlementResponse extends Payroc.PaginatedList {
    /** Array of dispute objects. */
    data: Payroc.Dispute[];
}
