// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { BankClient } from "../resources/bank/client/Client.js";
import { CardsClient } from "../resources/cards/client/Client.js";

export declare namespace PaymentFeaturesClient {
    export type Options = BaseClientOptions;
}

export class PaymentFeaturesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PaymentFeaturesClient.Options>;
    protected _cards: CardsClient | undefined;
    protected _bank: BankClient | undefined;

    constructor(options: PaymentFeaturesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get cards(): CardsClient {
        return (this._cards ??= new CardsClient(this._options));
    }

    public get bank(): BankClient {
        return (this._bank ??= new BankClient(this._options));
    }
}
