// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ownerId: 1
 *     }
 */
export interface DeleteOwnersRequest {
    /** Unique identifier that we assigned to the owner. */
    ownerId: number;
}
