// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         ownerId: 1,
 *         body: {
 *             firstName: "Jane",
 *             middleName: "Helen",
 *             lastName: "Doe",
 *             dateOfBirth: "1964-03-22",
 *             address: {
 *                 address1: "1 Example Ave.",
 *                 address2: "Example Address Line 2",
 *                 address3: "Example Address Line 3",
 *                 city: "Chicago",
 *                 state: "Illinois",
 *                 country: "US",
 *                 postalCode: "60056"
 *             },
 *             identifiers: [{
 *                     type: "nationalId",
 *                     value: "000-00-4320"
 *                 }],
 *             contactMethods: [{
 *                     type: "email",
 *                     value: "jane.doe@example.com"
 *                 }],
 *             relationship: {
 *                 equityPercentage: 48.5,
 *                 title: "CFO",
 *                 isControlProng: true,
 *                 isAuthorizedSignatory: false
 *             }
 *         }
 *     }
 */
export interface UpdateOwnersRequest {
    /** Unique identifier that we assigned to the owner. */
    ownerId: number;
    body: Payroc.Owner;
}
