// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         achDepositId: 1
 *     }
 */
export interface RetrieveAchDepositSettlementRequest {
    /** Unique identifier of the ACH deposit. */
    achDepositId: number;
}
