// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contactId: 1
 *     }
 */
export interface RetrieveContactsRequest {
    /** Unique identifier for the contact. */
    contactId: number;
}
