// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../index.js";

export interface ListFundingInstructionsResponse extends Payroc.PaginatedList {
    /** Array of fundingInstruction objects. */
    data: ListFundingInstructionsResponse.Data.Item[];
}

export namespace ListFundingInstructionsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item extends Payroc.Instruction {
            link?: Payroc.Link;
        }
    }
}
