// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         processingTerminalId: "1234001",
 *         paymentPlanId: "PlanRef8765"
 *     }
 */
export interface DeletePaymentPlansRequest {
    /** Unique identifier that we assigned to the terminal. */
    processingTerminalId: string;
    /** Unique identifier that the merchant assigned to the payment plan. */
    paymentPlanId: string;
}
