// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
 *         processingTerminalId: "1234001",
 *         libVersion: "1.1.0.123456",
 *         scenario: "payment"
 *     }
 */
export interface HostedFieldsCreateSessionRequest {
    /** Unique identifier that we assigned to the terminal. */
    processingTerminalId: string;
    /** Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency). */
    "Idempotency-Key": string;
    /**
     * Version of the Hosted Fields JavaScript library that you are using.
     *
     * The current production version is `1.6.0.172441`.
     */
    libVersion: string;
    /**
     * Indicates if a merchant wants to take a payment or tokenize a customer's payment details:
     *
     * - `payment` - The merchant wants to run a sale or run a sale and tokenize in the same transaction.
     * - `tokenization` - The merchant wants to save the customer's payment details to take a payment later or to update a customer's payment details that they've already saved.
     */
    scenario: HostedFieldsCreateSessionRequest.Scenario;
    /**
     * Unique identifier that represents a customer's payment details.
     *
     * If a merchant wants to update a customer's payment details that are linked to a secure token, include the secureTokenId in your request.
     */
    secureTokenId?: string;
}

export namespace HostedFieldsCreateSessionRequest {
    /**
     * Indicates if a merchant wants to take a payment or tokenize a customer's payment details:
     *
     * - `payment` - The merchant wants to run a sale or run a sale and tokenize in the same transaction.
     * - `tokenization` - The merchant wants to save the customer's payment details to take a payment later or to update a customer's payment details that they've already saved.
     */
    export const Scenario = {
        Payment: "payment",
        Tokenization: "tokenization",
    } as const;
    export type Scenario = (typeof Scenario)[keyof typeof Scenario];
}
