// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         processingTerminalId: "1234001",
 *         orderId: "OrderRef6543",
 *         operator: "Jane",
 *         cardholderName: "Sarah%20Hazel%20Hopper",
 *         first6: "453985",
 *         last4: "7062",
 *         tender: "ebt",
 *         dateFrom: "2024-07-01T15:30:00Z",
 *         dateTo: "2024-07-03T15:30:00Z",
 *         settlementState: "settled",
 *         settlementDate: "2024-07-02",
 *         before: "2571",
 *         after: "8516",
 *         limit: 1
 *     }
 *
 * @example
 *     {
 *         processingTerminalId: "1234001",
 *         orderId: "OrderRef6543",
 *         operator: "Jane",
 *         cardholderName: "Sarah%20Hazel%20Hopper",
 *         first6: "453985",
 *         last4: "7062",
 *         tender: "ebt",
 *         dateFrom: "2024-07-01T15:30:00Z",
 *         dateTo: "2024-07-03T15:30:00Z",
 *         settlementState: "settled",
 *         settlementDate: "2024-07-02",
 *         before: "2571",
 *         after: "8516",
 *         limit: 1
 *     }
 */
export interface ListRefundsRequest {
    /** Filter by terminal ID. */
    processingTerminalId?: string;
    /** Filter refunds by the unique identifier that the merchant assigned to the order. */
    orderId?: string;
    /** Filter refunds by the operator who initiated the request. */
    operator?: string;
    /** Filter refunds by cardholder name. */
    cardholderName?: string;
    /** Filter refunds by the first six digits of the card number. */
    first6?: string;
    /** Filter refunds by the last four digits of the card number. */
    last4?: string;
    /** Filter by tender type. */
    tender?: Payroc.payments.ListRefundsRequestTender;
    /** Filter refunds by the current status of the refund. */
    status?: Payroc.payments.ListRefundsRequestStatusItem | Payroc.payments.ListRefundsRequestStatusItem[];
    /** Filter by refunds processed after a specific date. The date format follows the ISO 8601 standard. */
    dateFrom?: string;
    /** Filter by refunds processed before a specific date. The date format follows the ISO 8601 standard. */
    dateTo?: string;
    /** Status of the settlement. */
    settlementState?: Payroc.payments.ListRefundsRequestSettlementState;
    /** Date the transaction was settled. */
    settlementDate?: string;
    /**
     * Return the previous page of results before the value that you specify.
     *
     * You can’t send the before parameter in the same request as the after parameter.
     */
    before?: string;
    /**
     * Return the next page of results after the value that you specify.
     *
     * You can’t send the after parameter in the same request as the before parameter.
     */
    after?: string;
    /** Limit the maximum number of results that we return for each page. */
    limit?: number;
}
