// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
 *         refundId: "CD3HN88U9F"
 *     }
 */
export interface ReverseRefundsRequest {
    /** Unique identifier that our gateway assigned to the refund. */
    refundId: string;
    /** Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency). */
    "Idempotency-Key": string;
}
