// This file was auto-generated by Fern from our API Definition.

export const ListEventSubscriptionsRequestStatus = {
    Registered: "registered",
    Suspended: "suspended",
    Failed: "failed",
} as const;
export type ListEventSubscriptionsRequestStatus =
    (typeof ListEventSubscriptionsRequestStatus)[keyof typeof ListEventSubscriptionsRequestStatus];
