// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as Payroc from "../../../index.js";

export declare namespace AuthClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AuthClient {
    protected readonly _options: NormalizedClientOptions<AuthClient.Options>;

    constructor(options: AuthClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Obtain an access token using client credentials
     *
     * @param {Payroc.RetrieveTokenAuthRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.auth.retrieveToken({
     *         "x-api-key": "x-api-key"
     *     })
     */
    public retrieveToken(
        request: Payroc.RetrieveTokenAuthRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<Payroc.GetTokenResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieveToken(request, requestOptions));
    }

    private async __retrieveToken(
        request: Payroc.RetrieveTokenAuthRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payroc.GetTokenResponse>> {
        const { "x-api-key": apiKey } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-api-key": apiKey }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.PayrocEnvironment.Production)
                        .identity,
                "authorize",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payroc.GetTokenResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PayrocError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/authorize");
    }
}
