// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         processingAccountId: "38765"
 *     }
 */
export interface RetrieveProcessingAccountsRequest {
    /** Unique identifier that we assigned to the processing account. */
    processingAccountId: string;
}
