// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains information about the payment details for the customer’s automated clearing house (ACH) transactions.
 */
export interface AchPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** For bank account details, send a value for accountType.
     */
    accountType?: AchPayload.AccountType | undefined;
    /**
     * Indicates how the customer authorized the ACH transaction. Send one of the following values:
     *
     * - `web` – Online transaction.
     * - `tel` – Telephone transaction.
     * - `ccd` – Corporate credit card or debit card transaction.
     * - `ppd` – Pre-arranged transaction.
     */
    secCode?: AchPayload.SecCode | undefined;
    /** Customer's name. */
    nameOnAccount: string;
    /**
     * Customer’s bank account number.
     * **Note:** In responses, our gateway shows only the last four digits of the account number, for example, `*****5929`.
     */
    accountNumber: string;
    /** Nine-digit number that identifies the customer's bank. */
    routingNumber: string;
}

export namespace AchPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** For bank account details, send a value for accountType.
     */
    export const AccountType = {
        Checking: "checking",
        Savings: "savings",
    } as const;
    export type AccountType = (typeof AccountType)[keyof typeof AccountType];
    /**
     * Indicates how the customer authorized the ACH transaction. Send one of the following values:
     *
     * - `web` – Online transaction.
     * - `tel` – Telephone transaction.
     * - `ccd` – Corporate credit card or debit card transaction.
     * - `ppd` – Pre-arranged transaction.
     */
    export const SecCode = {
        Web: "web",
        Tel: "tel",
        Ccd: "ccd",
        Ppd: "ppd",
    } as const;
    export type SecCode = (typeof SecCode)[keyof typeof SecCode];
}
