// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains the customer's account details.
 */
export interface AchSource {
    /** Customer's name. */
    nameOnAccount: string;
    /** Customer's account number. */
    accountNumber: string;
    /** Routing number of the customer's account. */
    routingNumber: string;
}
