// This file was auto-generated by Fern from our API Definition.

/**
 * Type of address.
 */
export interface AddressType {
    /** Type of address. */
    type: AddressType.Type;
}

export namespace AddressType {
    /** Type of address. */
    export const Type = {
        LegalAddress: "legalAddress",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
