// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the authorization.
 */
export interface Authorization {
    /** Unique identifier that we assigned to the authorization. */
    authorizationId?: number;
    /** Date that we received the authorization. The format of this value is **YYYY-MM-DD**. */
    createdDate?: string;
    /** Date that the authorization was last changed. The format of this value is **YYYY-MM-DD**. */
    lastModifiedDate?: string;
    /** Response from the issuing bank for the authorization. */
    authorizationResponse?: Authorization.AuthorizationResponse;
    /** Amount that the merchant requested for the authorization. We return the value in the currency's lowest denomination, for example, cents. */
    preauthorizationRequestAmount?: number;
    /** Currency of the authorization. The value for the currency follows the [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) standard. */
    currency?: string;
    batch?: Payroc.BatchSummary;
    card?: Payroc.CardSummary;
    merchant?: Payroc.MerchantSummary;
    transaction?: Payroc.TransactionSummary;
}

export namespace Authorization {
    /** Response from the issuing bank for the authorization. */
    export const AuthorizationResponse = {
        ActivityCountLimitExceeded: "activityCountLimitExceeded",
        AlreadyReversed: "alreadyReversed",
        Approved: "approved",
        ApproveVip: "approveVip",
        ApproveWithId: "approveWithId",
        CannotVerifyPin: "cannotVerifyPin",
        CardAuthenticationFailed: "cardAuthenticationFailed",
        CardTypeVerificationError: "cardTypeVerificationError",
        CashRequestExceedsIssuerLimit: "cashRequestExceedsIssuerLimit",
        CashServiceNotAvailable: "cashServiceNotAvailable",
        CidVerificationError: "cidVerificationError",
        ContactCardIssuer: "contactCardIssuer",
        CryptographicFailure: "cryptographicFailure",
        DailyThresholdExceeded: "dailyThresholdExceeded",
        DeclineCvv2Failure: "declineCvv2Failure",
        Deny: "deny",
        DenyAccountCanceled: "denyAccountCanceled",
        DenyClosedMerchant: "denyClosedMerchant",
        DenyNewCardIssued: "denyNewCardIssued",
        DenyPickUpCard: "denyPickUpCard",
        DestinationCannotBeFoundForRouting: "destinationCannotBeFoundForRouting",
        DoNotHonor: "doNotHonor",
        DuplicateTransmissionDetected: "duplicateTransmissionDetected",
        Error: "error",
        ExceedsWithdrawalAmountLimit: "exceedsWithdrawalAmountLimit",
        ExpiredCard: "expiredCard",
        FileTemporarilyUnavailable: "fileTemporarilyUnavailable",
        ForceStip: "forceStip",
        FormatError: "formatError",
        ForwardToIssuer: "forwardToIssuer",
        FunctionNotSupported: "functionNotSupported",
        HonorWithId: "honorWithId",
        IncorrectCvv: "incorrectCvv",
        IncorrectPin: "incorrectPin",
        IneligibleForResubmission: "ineligibleForResubmission",
        InsufficientFunds: "insufficientFunds",
        InvalidAccount: "invalidAccount",
        InvalidAccountNumber: "invalidAccountNumber",
        InvalidAmount: "invalidAmount",
        InvalidAuthorizationLifeCycle: "invalidAuthorizationLifeCycle",
        InvalidBillerInformation: "invalidBillerInformation",
        InvalidCardSecurityCode: "invalidCardSecurityCode",
        InvalidCurrencyCode: "invalidCurrencyCode",
        InvalidMerchant: "invalidMerchant",
        InvalidResponse: "invalidResponse",
        InvalidTransaction: "invalidTransaction",
        IssuerNotAvailable: "issuerNotAvailable",
        IssuerTimeout: "issuerTimeout",
        IssuerUnavailable: "issuerUnavailable",
        NoActionTaken: "noActionTaken",
        NoCardRecord: "noCardRecord",
        NoCheckingAccount: "noCheckingAccount",
        NoCreditAccount: "noCreditAccount",
        NoFinancialImpact: "noFinancialImpact",
        NoReasonToDecline: "noReasonToDecline",
        NoSavingsAccount: "noSavingsAccount",
        NoSuchIssuer: "noSuchIssuer",
        PartialApproval: "partialApproval",
        PartialAuthorization: "partialAuthorization",
        PickUpCard: "pickUpCard",
        PickUpCardSpecialCondition: "pickUpCardSpecialCondition",
        PinChangeRequestDeclined: "pinChangeRequestDeclined",
        PinCryptographicErrorFound: "pinCryptographicErrorFound",
        PinEntryTriesExceeded: "pinEntryTriesExceeded",
        PinNotChanged: "pinNotChanged",
        PleaseCallIssuer: "pleaseCallIssuer",
        ReenterTransaction: "reenterTransaction",
        ReferToCardIssuer: "referToCardIssuer",
        ReferToCardIssuerSpecialCondition: "referToCardIssuerSpecialCondition",
        RestrictedCard: "restrictedCard",
        Reversal: "reversal",
        ReversalDataInconsistent: "reversalDataInconsistent",
        RevokeAllAuthorizationsOrder: "revokeAllAuthorizationsOrder",
        ScheduledTransactionstoppedByCardholder: "scheduledTransactionstoppedByCardholder",
        SecurityViolation: "securityViolation",
        Successful: "successful",
        SurchargeAmountNotPermitted: "surchargeAmountNotPermitted",
        SuspectFraud: "suspectFraud",
        SystemMalfunction: "systemMalfunction",
        TransactionAmountExceedsApprovalAmount: "transactionAmountExceedsApprovalAmount",
        TransactionCannotBeCompleted: "transactionCannotBeCompleted",
        TransactionNotAllowedAtMerchant: "transactionNotAllowedAtMerchant",
        TransactionNotAllowedAtTerminal: "transactionNotAllowedAtTerminal",
        TransactionNotPermitted: "transactionNotPermitted",
        TransactionNotPermittedToCardholder: "transactionNotPermittedToCardholder",
        UnableToGoOnline: "unableToGoOnline",
        UnableToLocateRecordInFile: "unableToLocateRecordInFile",
        UnableToVerifyPin: "unableToVerifyPin",
        UnacceptablePin: "unacceptablePin",
        Unknown: "unknown",
        UnsafePin: "unsafePin",
    } as const;
    export type AuthorizationResponse = (typeof AuthorizationResponse)[keyof typeof AuthorizationResponse];
}
