// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the transaction.
 */
export interface BankTransferPaymentOrder extends Payroc.BankTransferPaymentOrderBase {
    breakdown?: Payroc.BankTransferBreakdown | undefined;
}
