// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the transaction.
 */
export interface BankTransferResult {
    /** Type of transaction. */
    type: BankTransferResult.Type;
    /** Status of the transaction. */
    status: BankTransferResult.Status;
    /**
     * Amount of the transaction.
     * **Note:** The amount is negative for a refund.
     */
    authorizedAmount?: number;
    currency?: Payroc.Currency;
    /**
     * Response from the processor.
     * - `A` - The processor approved the transaction.
     * - `D` - The processor declined the transaction.
     */
    responseCode?: string;
    /** Description of the response from the processor. */
    responseMessage: string;
    /** Original response code that the processor sent. */
    processorResponseCode?: string;
}

export namespace BankTransferResult {
    /** Type of transaction. */
    export const Type = {
        Payment: "payment",
        Refund: "refund",
        UnreferencedRefund: "unreferencedRefund",
        AccountVerification: "accountVerification",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Status of the transaction. */
    export const Status = {
        Ready: "ready",
        Pending: "pending",
        Declined: "declined",
        Complete: "complete",
        Admin: "admin",
        Reversal: "reversal",
        Returned: "returned",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
