// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface BankTransferPaymentPaginatedList extends Payroc.PaginatedList {
    /** Array of payments. */
    data?: Payroc.BankTransferPayment[] | undefined;
}
