// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface BankTransferRefund {
    /** Unique identifier that our gateway assigned to the refund. */
    refundId: string;
    /** Unique identifier that we assigned to the terminal. */
    processingTerminalId: string;
    order: Payroc.BankTransferRefundOrder;
    customer?: Payroc.BankTransferCustomer | undefined;
    /**
     * Polymorphic object that contains bank account information.
     *
     * The value of the type field determines which variant you should use:
     * -	`ach` - Automated Clearing House (ACH) details
     * -	`pad` - Pre-authorized debit (PAD) details
     */
    bankAccount: Payroc.BankTransferRefundBankAccount;
    payment?: Payroc.PaymentSummary | undefined;
    transactionResult: Payroc.BankTransferResult;
    /** Array of customField objects. */
    customFields?: Payroc.CustomField[] | undefined;
}
