// This file was auto-generated by Fern from our API Definition.

export interface BaseUsAnnual {
    /** Fee for the Platinum Security, this is returned in the lowest unit of currency. For example, cents. */
    amount?: number | undefined;
}
