// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the Platinum Security fee.
 */
export type BaseUsPlatinumSecurity = Payroc.BaseUsPlatinumSecurity.Monthly | Payroc.BaseUsPlatinumSecurity.Annual;

export namespace BaseUsPlatinumSecurity {
    export interface Monthly extends Payroc.BaseUsMonthly {
        billingFrequency: "monthly";
    }

    export interface Annual extends Payroc.BaseUsAnnual {
        billingFrequency: "annual";
    }

    /**
     * Object that contains information about the Platinum Security fee.
     */
    export type Request = Payroc.BaseUsPlatinumSecurity.Monthly | Payroc.BaseUsPlatinumSecurity.Annual;
}
