// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface BreakdownRequest extends Payroc.BreakdownBase {
    /** List of taxes. */
    taxes?: Payroc.Tax[];
}
