// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the customer’s payment card.
 */
export interface CardPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only for bank account details.
     */
    accountType?: CardPayload.AccountType | undefined;
    /**
     * Polymorphic object that contains payment card information.
     *
     * The value of the entryMethod parameter determines which variant you should use:
     * - `raw` - Unencrypted payment data directly from the device.
     * - `icc` - Payment data that the device captured from the chip.
     * - `keyed` - Payment data that the merchant entered manually.
     * - `swiped` - Payment data that the device captured from the magnetic strip.
     */
    cardDetails: Payroc.CardPayloadCardDetails;
}

export namespace CardPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only for bank account details.
     */
    export const AccountType = {
        Checking: "checking",
        Savings: "savings",
    } as const;
    export type AccountType = (typeof AccountType)[keyof typeof AccountType];
}
