// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface CardVerificationResult {
    /** Operator who requested to verify the card. */
    operator?: string | undefined;
    /** Unique identifier that we assigned to the terminal. */
    processingTerminalId: string;
    card?: Payroc.Card | undefined;
    /**
     * Indicates if the card details are valid:
     *
     * - `true` - Card details are valid.
     * - `false` - Card details are not valid.
     */
    verified: boolean;
    transactionResult?: Payroc.TransactionResult | undefined;
}
