// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the customer’s payment card.
 */
export interface CardPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only for bank account details.
     */
    accountType?: CardPayload.AccountType;
    /** Object that contains the details of the payment card. */
    cardDetails: Payroc.CardPayloadCardDetails;
}

export namespace CardPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only for bank account details.
     */
    export const AccountType = {
        Checking: "checking",
        Savings: "savings",
    } as const;
    export type AccountType = (typeof AccountType)[keyof typeof AccountType];
}
