// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the card.
 */
export interface CardInfo {
    /** Card brand of the card, for example, Visa. */
    type: string;
    /** Masked card number. Our gateway shows only the first six digits and the last four digits of the card number, for example, 548010******5929. */
    cardNumber: string;
    /** Country of the issuing bank. The value for the country follows the [ISO-3166-1](https://www.iso.org/iso-3166-country-codes.html) standard. */
    country?: string;
    currency?: Payroc.Currency;
    /** Indicates if the card is a debit card. */
    debit?: boolean;
    surcharging?: Payroc.Surcharging;
}
