// This file was auto-generated by Fern from our API Definition.

export interface CommonFunding {
    /** Indicates if the processing account can receive funds. */
    status?: CommonFunding.Status;
    /**
     * Indicates when funds are sent to the funding account.
     *
     * If you send a value of `sameDay` or `nextDay`, provide a value for acceleratedFundingFee.
     *
     * **Note:** If you send a value of `sameday`, funding includes all transactions the merchant ran before the ACH cut-off time.
     */
    fundingSchedule?: CommonFunding.FundingSchedule;
    /**
     * Monthly fee in cents for accelerated funding. The value is in the currency's lowest denomination, for example, cents.
     *
     * We apply this fee if the value for fundingSchedule is `sameday` or `nextday`.
     */
    acceleratedFundingFee?: number;
    /** Indicates if we collect fees from the merchant's account each day. */
    dailyDiscount?: boolean;
}

export namespace CommonFunding {
    /** Indicates if the processing account can receive funds. */
    export const Status = {
        Enabled: "enabled",
        Disabled: "disabled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /**
     * Indicates when funds are sent to the funding account.
     *
     * If you send a value of `sameDay` or `nextDay`, provide a value for acceleratedFundingFee.
     *
     * **Note:** If you send a value of `sameday`, funding includes all transactions the merchant ran before the ACH cut-off time.
     */
    export const FundingSchedule = {
        Standard: "standard",
        Nextday: "nextday",
        Sameday: "sameday",
    } as const;
    export type FundingSchedule = (typeof FundingSchedule)[keyof typeof FundingSchedule];
}
