// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains information about the convenience fee for the transaction.
 */
export interface ConvenienceFee {
    /**
     * If the merchant added a convenience fee, this value indicates the amount of the convenience fee
     * in the currency’s lowest denomination, for example, cents.
     */
    amount: number;
}
