// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains information about the payment details in the customer’s digital wallet.
 */
export interface DigitalWalletPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only for bank account details.
     */
    accountType?: DigitalWalletPayload.AccountType | undefined;
    /**
     * Provider of the digital wallet. Send one of the following values:
     * - `apple` - For more information about how to integrate with Apple Pay, go to [Apple Pay®](https://docs.payroc.com/guides/take-payments/apple-pay).
     * - `google` - For more information about how to integrate with google Pay, go to [Google Pay®](https://docs.payroc.com/guides/take-payments/google-pay).
     */
    serviceProvider: DigitalWalletPayload.ServiceProvider;
    /** Cardholder’s name. */
    cardholderName?: string | undefined;
    /** Encrypted data of the digital wallet. */
    encryptedData: string;
}

export namespace DigitalWalletPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only for bank account details.
     */
    export const AccountType = {
        Checking: "checking",
        Savings: "savings",
    } as const;
    export type AccountType = (typeof AccountType)[keyof typeof AccountType];
    /**
     * Provider of the digital wallet. Send one of the following values:
     * - `apple` - For more information about how to integrate with Apple Pay, go to [Apple Pay®](https://docs.payroc.com/guides/take-payments/apple-pay).
     * - `google` - For more information about how to integrate with google Pay, go to [Google Pay®](https://docs.payroc.com/guides/take-payments/google-pay).
     */
    export const ServiceProvider = {
        Apple: "apple",
        Google: "google",
    } as const;
    export type ServiceProvider = (typeof ServiceProvider)[keyof typeof ServiceProvider];
}
