// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the dispute.
 */
export interface Dispute {
    /** Unique identifier that we assigned to the dispute. */
    disputeId?: number | undefined;
    /** Type of dispute. */
    disputeType?: Dispute.DisputeType | undefined;
    /** Object that contains information about the current status of the dispute. */
    currentStatus?: Dispute.CurrentStatus | undefined;
    /** Date that we received the dispute. The format of this value is **YYYY-MM-DD**. */
    createdDate?: string | undefined;
    /** Date that the dispute was last changed. The format of this value is **YYYY-MM-DD**. */
    lastModifiedDate?: string | undefined;
    /** Date that the acquiring bank received the dispute. The format of this value is **YYYY-MM-DD**. */
    receivedDate?: string | undefined;
    /** Description of the dispute. */
    description?: string | undefined;
    /** Reference number from the acquiring bank. */
    referenceNumber?: string | undefined;
    /** Dispute amount. We return the value in the currency's lowest denomination, for example, cents. */
    disputeAmount?: number | undefined;
    /** Value of the fees for the dispute. We return the value in the currency's lowest denomination, for example, cents. */
    feeAmount?: number | undefined;
    /** Indicates if this is the first dispute for the transaction. */
    firstDispute?: boolean | undefined;
    /** Authorization code of the transaction that the dispute is linked to. */
    authorizationCode?: string | undefined;
    /** Currency of the transaction that the dispute is linked to. The value for the currency follows the [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) standard. */
    currency?: string | undefined;
    card?: Payroc.CardSummary | undefined;
    merchant?: Payroc.MerchantSummary | undefined;
    transaction?: Payroc.TransactionSummary | undefined;
}

export namespace Dispute {
    /** Type of dispute. */
    export const DisputeType = {
        Prearbitration: "prearbitration",
        IssuerReversal: "issuerReversal",
        FirstDisputeWithReversal: "firstDisputeWithReversal",
        FirstDispute: "firstDispute",
    } as const;
    export type DisputeType = (typeof DisputeType)[keyof typeof DisputeType];

    /**
     * Object that contains information about the current status of the dispute.
     */
    export interface CurrentStatus extends Payroc.DisputeStatus {
        link?: Payroc.Link | undefined;
    }
}
