// This file was auto-generated by Fern from our API Definition.

export interface FourHundredThree {
    /** URI reference identifying the problem type */
    type: string;
    /** Short description of the issue. */
    title: string;
    /** Http status code */
    status: number;
    /** Explanation of the problem */
    detail: string;
    /** Resource path the action was attempted on */
    instance?: string | undefined;
    /** Resource the action was attempted on */
    resource?: string | undefined;
}
