// This file was auto-generated by Fern from our API Definition.

export interface FourHundredThirteen {
    /** URI reference identifying the problem type */
    type: string;
    /** Short description of the issue. */
    title: string;
    /** Http status code */
    status: number;
    /** Explanation of the problem */
    detail: string;
}
