// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface FundingRecipient {
    /** Unique identifier that we assigned to the funding recipient. */
    recipientId?: number | undefined;
    /** Indicates if we have approved the funding recipient. */
    status?: FundingRecipient.Status | undefined;
    /** Date the funding recipient was created. */
    createdDate?: string | undefined;
    /** Date the funding recipient was last modified. */
    lastModifiedDate?: string | undefined;
    /** Type or legal structure of the funding recipient. */
    recipientType: FundingRecipient.RecipientType;
    /** Employer identification number (EIN) or Social Security number (SSN). */
    taxId: string;
    /** Government identifier of the charity. */
    charityId?: string | undefined;
    /** Legal name of the business or organization. */
    doingBusinessAs: string;
    /** Polymorphic object that contains address information for a funding recipient. */
    address: Payroc.Address;
    /**
     * Array of polymorphic objects, which contain contact information.
     *
     * The value of the type parameter determines which variant you should use:
     * -	`email` - Email address
     * -	`phone` - Phone number
     * -	`mobile` - Mobile number
     * -	`fax` - Fax number
     */
    contactMethods: Payroc.ContactMethod[];
    /** [Metadata](https://docs.payroc.com/api/metadata) object you can use to include custom data with your request. */
    metadata?: Record<string, string> | undefined;
    /** Array of owner objects associated with the funding recipient. */
    owners?: FundingRecipient.Owners.Item[] | undefined;
    /** Array of fundingAccount objects associated with the funding recipient. */
    fundingAccounts?: FundingRecipient.FundingAccounts.Item[] | undefined;
}

export namespace FundingRecipient {
    /** Indicates if we have approved the funding recipient. */
    export const Status = {
        Approved: "approved",
        Rejected: "rejected",
        Pending: "pending",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Type or legal structure of the funding recipient. */
    export const RecipientType = {
        PrivateCorporation: "privateCorporation",
        PublicCorporation: "publicCorporation",
        NonProfit: "nonProfit",
        Government: "government",
        PrivateLlc: "privateLlc",
        PublicLlc: "publicLlc",
        PrivatePartnership: "privatePartnership",
        PublicPartnership: "publicPartnership",
        SoleProprietor: "soleProprietor",
    } as const;
    export type RecipientType = (typeof RecipientType)[keyof typeof RecipientType];
    export type Owners = Owners.Item[];

    export namespace Owners {
        export interface Item {
            /** Unique identifier of the owner. */
            ownerId?: number | undefined;
            /** Object that contains HATEOAS links for the resource. */
            link?: Item.Link | undefined;
        }

        export namespace Item {
            /**
             * Object that contains HATEOAS links for the resource.
             */
            export interface Link {
                /** Indicates the relationship between the current resource and the target resource. */
                rel?: string | undefined;
                /** URL of the target resource. */
                href?: string | undefined;
                /** HTTP method that you need to use with the target resource. */
                method?: string | undefined;
            }
        }
    }

    export type FundingAccounts = FundingAccounts.Item[];

    export namespace FundingAccounts {
        export interface Item {
            /** Unique identifier of the funding account. */
            fundingAccountId?: number | undefined;
            /** Status of the funding account. */
            status?: Item.Status | undefined;
            /** Object that contains HATEOAS links for the resource. */
            link?: Item.Link | undefined;
        }

        export namespace Item {
            /** Status of the funding account. */
            export const Status = {
                Approved: "approved",
                Rejected: "rejected",
                Pending: "pending",
                Hold: "hold",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];

            /**
             * Object that contains HATEOAS links for the resource.
             */
            export interface Link {
                /** Indicates the relationship between the current resource and the target resource. */
                rel?: string | undefined;
                /** URL of the target resource. */
                href?: string | undefined;
                /** HTTP method that you need to use with the target resource. */
                method?: string | undefined;
            }
        }
    }
}
