// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains the host processor configuration.
 */
export type HostConfigurationConfiguration = Payroc.HostConfigurationConfiguration.Tsys;

export namespace HostConfigurationConfiguration {
    export interface Tsys extends Payroc.Tsys {
        processor: "tsys";
    }
}
