// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains the fees for American Express transactions.
 */
export type InterchangePlusFeesAmex = Payroc.InterchangePlusFeesAmex.OptBlue | Payroc.InterchangePlusFeesAmex.Direct;

export namespace InterchangePlusFeesAmex {
    export interface OptBlue extends Payroc.InterchangePlusAmexOptBlue {
        type: "optBlue";
    }

    export interface Direct extends Payroc.InterchangePlusAmexDirect {
        type: "direct";
    }
}
