// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains the fees for American Express transactions.
 */
export type InterchangePlusPlusFeesAmex =
    | Payroc.InterchangePlusPlusFeesAmex.OptBlue
    | Payroc.InterchangePlusPlusFeesAmex.Direct;

export namespace InterchangePlusPlusFeesAmex {
    export interface OptBlue extends Payroc.InterchangePlusPlusAmexOptBlue {
        type: "optBlue";
    }

    export interface Direct extends Payroc.InterchangePlusPlusAmexDirect {
        type: "direct";
    }
}
