// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about Interchange Plus with three tiers.
 */
export interface InterchangePlusTiered3 {
    /** Object that contains information about the fees. */
    fees: InterchangePlusTiered3.Fees;
}

export namespace InterchangePlusTiered3 {
    /**
     * Object that contains information about the fees.
     */
    export interface Fees {
        /** Object that contains the fees for Mastercard, Visa, and Discover transactions. */
        mastercardVisaDiscover: Payroc.QualRates;
        /** Object that contains the fees for American Express transactions. */
        amex?: Payroc.InterchangePlusTiered3FeesAmex;
        pinDebit?: Payroc.PinDebit;
        electronicBenefitsTransfer?: Payroc.ElectronicBenefitsTransfer;
        enhancedInterchange?: Payroc.EnhancedInterchange;
        specialityCards?: Payroc.SpecialityCards;
    }
}
