// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about Interchange Plus Plus.
 */
export interface InterchangePlusPlusUs52 {
    /** Object that contains information about the fees. */
    fees: InterchangePlusPlusUs52.Fees;
}

export namespace InterchangePlusPlusUs52 {
    /**
     * Object that contains information about the fees.
     */
    export interface Fees {
        /** Object that contains the fees for Mastercard, Visa, and Discover transactions. */
        mastercardVisaDiscover: Payroc.QualRates;
        /** Object that contains the fees for American Express transactions. */
        amex?: Payroc.InterchangePlusPlusUs52FeesAmex | undefined;
        pinDebit?: Payroc.PinDebit | undefined;
        electronicBenefitsTransfer?: Payroc.ElectronicBenefitsTransfer | undefined;
        specialityCards?: Payroc.SpecialityCards | undefined;
    }
}
