// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export type KeyedCardDetailsPinDetails = Payroc.KeyedCardDetailsPinDetails.Dukpt;

export namespace KeyedCardDetailsPinDetails {
    export interface Dukpt extends Payroc.DukptPinDetails {
        dataFormat: "dukpt";
    }
}
