// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Polymorphic object that contains information about the customer's PIN.
 */
export type KeyedCardDetailsPinDetails = Payroc.KeyedCardDetailsPinDetails.Dukpt;

export namespace KeyedCardDetailsPinDetails {
    export interface Dukpt extends Payroc.DukptPinDetails {
        dataFormat: "dukpt";
    }
}
