// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the merchant.
 */
export interface MerchantSummary {
    /** Unique identifier that the processor assigned to the merchant. */
    merchantId?: string;
    /** Trading name of the business. */
    doingBusinessAs?: string;
    /** Unique identifier that we assigned to the processing account. */
    processingAccountId?: number;
    link?: Payroc.Link;
}
