// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the order.
 */
export interface MultiUsePaymentLinkOrder {
    /** A brief description of the transaction. */
    description?: string | undefined;
    /**
     * Polymorphic object that indicates who enters the amount for the payment link.
     *
     * The value of the type parameter determines which variant you should use:
     * -	`prompt` - Customer enters the amount.
     * -	`preset` - Merchant sets the amount.
     */
    charge: Payroc.MultiUsePaymentLinkOrderCharge;
}
