// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about a multi-use payment link.
 */
export interface MultiUsePaymentLink {
    /** Unique identifier that we assigned to the payment link. */
    paymentLinkId?: string | undefined;
    /** Unique identifier that the merchant assigned to the payment. */
    merchantReference: string;
    order: Payroc.MultiUsePaymentLinkOrder;
    /** Type of transaction. */
    authType: MultiUsePaymentLink.AuthType;
    /**
     * Payment methods that the merchant accepts.
     * **Note:** If a payment is a pre-authorization, the customer must pay by card.
     */
    paymentMethods: MultiUsePaymentLink.PaymentMethods.Item[];
    /**
     * Array of customLabel objects.
     * **Note:** You can change the label of the payment button only.
     */
    customLabels?: Payroc.CustomLabel[] | undefined;
    assets?: Payroc.PaymentLinkAssets | undefined;
    /**
     * Status of the payment link. The value is one of the following:
     * - `active` - Payment link is active.
     * - `completed` - Customer has paid.
     * - `deactivated` - Merchant has deactivated the link.
     * - `expired` - Payment link has expired.
     */
    status?: MultiUsePaymentLink.Status | undefined;
    /** Date that the merchant created the link. The format of this value is **YYYY-MM-DD**. */
    createdOn?: string | undefined;
    /** Last date that the customer can use the payment link. The format of this value is **YYYY-MM-DD**. */
    expiresOn?: string | undefined;
    credentialOnFile?: Payroc.CredentialOnFile | undefined;
}

export namespace MultiUsePaymentLink {
    /** Type of transaction. */
    export const AuthType = {
        Sale: "sale",
        PreAuthorization: "preAuthorization",
    } as const;
    export type AuthType = (typeof AuthType)[keyof typeof AuthType];
    export type PaymentMethods = PaymentMethods.Item[];

    export namespace PaymentMethods {
        export const Item = {
            Card: "card",
            BankTransfer: "bankTransfer",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /**
     * Status of the payment link. The value is one of the following:
     * - `active` - Payment link is active.
     * - `completed` - Customer has paid.
     * - `deactivated` - Merchant has deactivated the link.
     * - `expired` - Payment link has expired.
     */
    export const Status = {
        Active: "active",
        Completed: "completed",
        Deactivated: "deactivated",
        Expired: "expired",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
