// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export type Notification = Payroc.Notification.Webhook;

export namespace Notification {
    export interface Webhook extends Payroc.Webhook {
        type: "webhook";
    }
}
