// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains the customer's account details.
 */
export interface PadBankAccount {
    /** Customer's name. */
    nameOnAccount: string;
    /** Customer's bank account number. We mask all digits except the last four digits. */
    accountNumber: string;
    /** Five-digit code that represents the customer's banking branch. */
    transitNumber: string;
    /** Three-digit code that represents the customer's bank. */
    institutionNumber: string;
    secureToken?: Payroc.SecureTokenSummary | undefined;
}
