// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the partially-encrypted card data for keyed transactions.
 */
export interface PartiallyEncryptedKeyedDataFormat {
    device: Payroc.EncryptionCapableDevice;
    /** Encrypted card number. */
    encryptedPan: string;
    /**
     * Masked card number.
     * The gateway shows only the first six digits and the last four digits of the account number. For example, `453985******7062`.
     */
    maskedPan: string;
    /** Expiry date of the customer’s card. */
    expiryDate: string;
    /** Security code of the customer’s card. */
    cvv?: string;
    /** Encrypted security code data. */
    cvvEncrypted?: string;
    /** Issue number of the customer’s card. */
    issueNumber?: string;
}
