// This file was auto-generated by Fern from our API Definition.

/**
 * A Patch Test Operation.
 */
export interface PatchTest {
    /**
     * Location of the value that you want to test.
     * The format for this value is JSON Pointer.
     */
    path: string;
    value?: unknown | undefined;
}
