// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * A JSON Patch document as defined by RFC 6902.
 */
export type PatchRequest = Payroc.PatchDocument[];
