// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface Payment {
    /** Unique identifier that our gateway assigned to the transaction. */
    paymentId: string;
    /** Unique identifier of the terminal that initiated the transaction. */
    processingTerminalId: string;
    /** Operator who initiated the request. */
    operator?: string | undefined;
    order: Payroc.PaymentOrder;
    customer?: Payroc.RetrievedCustomer | undefined;
    card: Payroc.Card;
    /**
     * Array of refundSummary objects.
     * Each object contains information about refunds linked to the transaction.
     */
    refunds?: Payroc.RefundSummary[] | undefined;
    supportedOperations?: Payroc.SupportedOperations | undefined;
    transactionResult: Payroc.TransactionResult;
    /** Array of customField objects. */
    customFields?: Payroc.CustomField[] | undefined;
}
