// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export type PaymentMethodsItem = Payroc.PaymentMethodsItem.Ach;

export namespace PaymentMethodsItem {
    export interface Ach extends Payroc.PaymentMethodAch {
        type: "ach";
    }
}
