// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains shareable assets for the payment link.
 */
export interface PaymentLinkAssets {
    /** URL of the payment link. */
    paymentUrl: string;
    /** HTML code for the payment link. You can embed the HTML code in the merchant's website. */
    paymentButton: string;
}
