// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export type PaymentLinkPaginatedListDataItem =
    | Payroc.PaymentLinkPaginatedListDataItem.MultiUse
    | Payroc.PaymentLinkPaginatedListDataItem.SingleUse;

export namespace PaymentLinkPaginatedListDataItem {
    export interface MultiUse extends Payroc.MultiUsePaymentLink {
        type: "multiUse";
    }

    export interface SingleUse extends Payroc.SingleUsePaymentLink {
        type: "singleUse";
    }

    export type Request =
        | Payroc.PaymentLinkPaginatedListDataItem.MultiUse
        | Payroc.PaymentLinkPaginatedListDataItem.SingleUse;
}
