// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface PaymentPlan extends Payroc.PaymentPlanBase {
    setupOrder?: Payroc.PaymentPlanSetupOrder;
    recurringOrder?: Payroc.PaymentPlanRecurringOrder;
}
