// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Polymorphic object that contains information about when and how the terminal closes the batch.
 *
 * The value of the batchCloseType field determines which variant you should use:
 * -	`automatic` - Terminal automatically closes the batch at a specific time each day.
 * - `manual` - Merchant uses the terminal to manually close the batch.
 */
export type ProcessingTerminalBatchClosure =
    | Payroc.ProcessingTerminalBatchClosure.Automatic
    | Payroc.ProcessingTerminalBatchClosure.Manual;

export namespace ProcessingTerminalBatchClosure {
    export interface Automatic extends Payroc.SchemasAutomaticBatchClose {
        batchCloseType: "automatic";
    }

    export interface Manual extends Payroc.SchemasManualBatchClose {
        batchCloseType: "manual";
    }
}
