// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the retrieved refund.
 */
export interface RetrievedRefund {
    /** Unique identifier that our gateway assigned to the refund. */
    refundId: string;
    /** Unique identifier that we assigned to the terminal. */
    processingTerminalId: string;
    /** Operator who requested the refund. */
    operator?: string;
    order: Payroc.RefundOrder;
    customer?: Payroc.RetrievedCustomer;
    card: Payroc.RetrievedCard;
    payment?: Payroc.PaymentSummary;
    supportedOperations?: Payroc.SupportedOperations;
    transactionResult: Payroc.TransactionResult;
    /** Array of customField objects. */
    customFields?: Payroc.CustomField[];
}
