// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains information about saving the customer’s payment details.
 */
export interface SchemasCredentialOnFile {
    /** Indicates if the merchant uses a third-party vault to store the customer’s payment details. */
    externalVault?: boolean;
    /** Indicates if our gateway should tokenize the customer’s payment details as part of the transaction. */
    tokenize?: boolean;
    /**
     * Unique identifier that the merchant creates for the secure token that represents the customer’s payment details.
     * **Note:** If you do not send a value for the **secureTokenId**, our gateway generates a unique identifier for the token.
     */
    secureTokenId?: string;
    /**
     * Indicates how the merchant can use the customer’s card details, as agreed by the customer:
     *
     * - `unscheduled` - Transactions for a fixed or variable amount that are run at a certain pre-defined event.
     * - `recurring` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Recurring transactions don’t have a fixed duration and run until the customer cancels the agreement.
     * - `installment` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Installment transactions have a fixed duration.
     *
     * **Note:** If you send a value for **mitAgreement**, you must send the **standingInstructions** object in the **paymentOrder** object.
     */
    mitAgreement?: SchemasCredentialOnFile.MitAgreement;
}

export namespace SchemasCredentialOnFile {
    /**
     * Indicates how the merchant can use the customer’s card details, as agreed by the customer:
     *
     * - `unscheduled` - Transactions for a fixed or variable amount that are run at a certain pre-defined event.
     * - `recurring` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Recurring transactions don’t have a fixed duration and run until the customer cancels the agreement.
     * - `installment` - Transactions for a fixed amount that are run at regular intervals, for example, monthly. Installment transactions have a fixed duration.
     *
     * **Note:** If you send a value for **mitAgreement**, you must send the **standingInstructions** object in the **paymentOrder** object.
     */
    export const MitAgreement = {
        Unscheduled: "unscheduled",
        Recurring: "recurring",
        Installment: "installment",
    } as const;
    export type MitAgreement = (typeof MitAgreement)[keyof typeof MitAgreement];
}
