// This file was auto-generated by Fern from our API Definition.

/**
 * Time zone of the terminal.
 * **Note**: If you don't send a value for this parameter, we use the time zone of the processing account.
 */
export const SchemasTimezone = {
    PacificMidway: "Pacific/Midway",
    PacificHonolulu: "Pacific/Honolulu",
    AmericaAnchorage: "America/Anchorage",
    AmericaLosAngeles: "America/Los_Angeles",
    AmericaDenver: "America/Denver",
    AmericaPhoenix: "America/Phoenix",
    AmericaChicago: "America/Chicago",
    AmericaIndianaIndianapolis: "America/Indiana/Indianapolis",
    AmericaNewYork: "America/New_York",
} as const;
export type SchemasTimezone = (typeof SchemasTimezone)[keyof typeof SchemasTimezone];
