// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains information about the secure token that represents the customer’s payment details.
 */
export interface SecureTokenPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only if the secure token represents bank account details.
     */
    accountType?: SecureTokenPayload.AccountType | undefined;
    /** Unique token that the gateway assigned to the payment details. */
    token: string;
    /**
     * Indicates how the customer authorized the ACH transaction. Send one of the following values:
     *
     * - `web` – Online transaction.
     * - `tel` – Telephone transaction.
     * - `ccd` – Corporate credit card or debit card transaction.
     * - `ppd` – Pre-arranged transaction.
     */
    secCode?: SecureTokenPayload.SecCode | undefined;
}

export namespace SecureTokenPayload {
    /**
     * Indicates the customer’s account type.
     *
     * **Note:** Send a value for accountType only if the secure token represents bank account details.
     */
    export const AccountType = {
        Checking: "checking",
        Savings: "savings",
    } as const;
    export type AccountType = (typeof AccountType)[keyof typeof AccountType];
    /**
     * Indicates how the customer authorized the ACH transaction. Send one of the following values:
     *
     * - `web` – Online transaction.
     * - `tel` – Telephone transaction.
     * - `ccd` – Corporate credit card or debit card transaction.
     * - `ppd` – Pre-arranged transaction.
     */
    export const SecCode = {
        Web: "web",
        Tel: "tel",
        Ccd: "ccd",
        Ppd: "ppd",
    } as const;
    export type SecCode = (typeof SecCode)[keyof typeof SecCode];
}
