// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the Hardware Advantage Plan.
 */
export type ServiceUs50 = Payroc.ServiceUs50.HardwareAdvantagePlan;

export namespace ServiceUs50 {
    export interface HardwareAdvantagePlan extends Payroc.HardwareAdvantagePlan {
        name: "hardwareAdvantagePlan";
    }
}
