// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the settlement.
 */
export interface SettledSummary {
    /** Processor that settled the transaction. */
    settledBy?: string | undefined;
    /** Date that the processor settled the transaction. The format of this value is **YYYY-MM-DD**. */
    achDate?: string | undefined;
    /** Unique identifier of the ACH deposit. */
    achDepositId?: number | undefined;
    link?: Payroc.Link | undefined;
}
