// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains the signature for the transaction.
 * **Note:** If the merchant previously added a signature to the transaction, they can’t adjust or delete the signature.
 */
export interface SignatureAdjustment {
    /** Cardholder’s signature. For more information about the format of the signature, see Special Fields and Parameters. */
    cardholderSignature: string;
}
