// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Polymorphic object that contains information about how we captured the owner's signature.
 *
 * The value of the type parameter determines which variant you should use:
 * -	`requestedViaDirectLink` - Request signature using a link.
 * -	`requestedViaEmail` - Request signature by email.
 */
export type Signature = Payroc.Signature.RequestedViaDirectLink | Payroc.Signature.RequestedViaEmail;

export namespace Signature {
    export interface RequestedViaDirectLink extends Payroc.SignatureByDirectLink {
        type: "requestedViaDirectLink";
    }

    export interface RequestedViaEmail extends Payroc.SignatureByEmail {
        type: "requestedViaEmail";
    }
}
