// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface SignatureInstruction extends Payroc.DeviceInstruction {
    /** Unique identifier that our gateway assigned to the instruction. */
    signatureInstructionId?: string;
}
