// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Polymorphic object that contains the payment method that we tokenized.
 *
 * The value of the type parameter determines which variant you should use:
 * -	`ach` - Automated Clearing House (ACH) details
 * -	`pad` - Pre-authorized debit (PAD) details
 * -	`card` - Payment card details
 */
export type SingleUseTokenSource =
    | Payroc.SingleUseTokenSource.Ach
    | Payroc.SingleUseTokenSource.Pad
    | Payroc.SingleUseTokenSource.Card;

export namespace SingleUseTokenSource {
    export interface Ach extends Payroc.AchSource {
        type: "ach";
    }

    export interface Pad extends Payroc.PadSource {
        type: "pad";
    }

    export interface Card extends Payroc.CardSource {
        type: "card";
    }
}
