// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Polymorphic object that contains information about a customer's PIN.
 *
 * The value of the dataFormat parameter determines which variant you should use:
 * - `dukpt` - PIN information is encrypted.
 * - `raw` - PIN information is unencrypted.
 */
export type SingleUseTokenPayloadPinDetails =
    | Payroc.SingleUseTokenPayloadPinDetails.Dukpt
    | Payroc.SingleUseTokenPayloadPinDetails.Raw;

export namespace SingleUseTokenPayloadPinDetails {
    export interface Dukpt extends Payroc.DukptPinDetails {
        dataFormat: "dukpt";
    }

    export interface Raw extends Payroc.RawPinDetails {
        dataFormat: "raw";
    }
}
