// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Indicates whether the merchant or the customer enters the amount for the transaction.
 */
export type SingleUsePaymentLinkOrderCharge =
    | Payroc.SingleUsePaymentLinkOrderCharge.Prompt
    | Payroc.SingleUsePaymentLinkOrderCharge.Preset;

export namespace SingleUsePaymentLinkOrderCharge {
    export interface Prompt extends Payroc.PromptPaymentLinkCharge {
        type: "prompt";
    }

    export interface Preset extends Payroc.PresetPaymentLinkCharge {
        type: "preset";
    }
}
