// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * If you don't use our Subscriptions mechanism, include this section to configure your standing/recurring orders.
 */
export interface StandingInstructions {
    /** Position of the transaction in the payment plan sequence. */
    sequence: StandingInstructions.Sequence;
    /**
     * Indicates the type of payment instruction.
     *
     * - 'unscheduled' – The payment is not part of a regular billing cycle.
     * - 'recurring' – The payment is part of a regular billing cycle with no end date.
     * - 'installment' – The payment is part of a regular billing cycle with an end date.
     */
    processingModel: StandingInstructions.ProcessingModel;
    /** Object that contains information about the initial payment for the payment instruction. */
    referenceDataOfFirstTxn?: Payroc.FirstTxnReferenceData | undefined;
}

export namespace StandingInstructions {
    /** Position of the transaction in the payment plan sequence. */
    export const Sequence = {
        First: "first",
        Subsequent: "subsequent",
    } as const;
    export type Sequence = (typeof Sequence)[keyof typeof Sequence];
    /**
     * Indicates the type of payment instruction.
     *
     * - 'unscheduled' – The payment is not part of a regular billing cycle.
     * - 'recurring' – The payment is part of a regular billing cycle with no end date.
     * - 'installment' – The payment is part of a regular billing cycle with an end date.
     */
    export const ProcessingModel = {
        Unscheduled: "unscheduled",
        Recurring: "recurring",
        Installment: "installment",
    } as const;
    export type ProcessingModel = (typeof ProcessingModel)[keyof typeof ProcessingModel];
}
