// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface SubscriptionPaymentOrderRequest extends Payroc.SubscriptionPaymentOrderBase {
    breakdown?: Payroc.SubscriptionOrderBreakdownRequest;
}
