// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

export interface SubscriptionPayment {
    /** Unique identifier that the merchant assigned to the subscription. */
    subscriptionId: string;
    /** Unique identifier of the terminal that the subscription is linked to. */
    processingTerminalId: string;
    payment: Payroc.PaymentSummary;
    secureToken: Payroc.SecureTokenSummary;
    currentState: Payroc.SubscriptionState;
    /** Array of customField objects. */
    customFields?: Payroc.CustomField[];
}
