// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Polymorphic object that contains information about the customer's PIN.
 */
export type SwipedCardDetailsPinDetails = Payroc.SwipedCardDetailsPinDetails.Dukpt;

export namespace SwipedCardDetailsPinDetails {
    export interface Dukpt extends Payroc.DukptPinDetails {
        dataFormat: "dukpt";
    }
}
