// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains the 3-D Secure information from a third party.
 */
export interface ThirdPartyThreeDSecure {
    /** E-commerce indicator (ECI) result of a the 3-D Secure check. */
    eci: ThirdPartyThreeDSecure.Eci;
    /** Unique transaction identifier that the merchant assigned to the transaction and sent in the authentication request. */
    xid?: string;
    /** Cardholder Authentication Verification Value (CAVV) that the card issuer provided to prove that they authorized the online payment. */
    cavv?: string;
    /** Directory Server Transaction ID that the processor assigned to the request. */
    dsTransactionId?: string;
}

export namespace ThirdPartyThreeDSecure {
    /** E-commerce indicator (ECI) result of a the 3-D Secure check. */
    export const Eci = {
        FullyAuthenticated: "fullyAuthenticated",
        AttemptedAuthentication: "attemptedAuthentication",
    } as const;
    export type Eci = (typeof Eci)[keyof typeof Eci];
}
