// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about tiered pricing with six tiers.
 */
export interface Tiered6 {
    /** Object that contains information about the fees. */
    fees: Tiered6.Fees;
}

export namespace Tiered6 {
    /**
     * Object that contains information about the fees.
     */
    export interface Fees {
        /** Object that contains the fees for Mastercard, Visa, and Discover transactions. */
        mastercardVisaDiscover: Payroc.QualRatesWithPremiumAndRegulated;
        /** Object that contains the fees for American Express transactions. */
        amex?: Payroc.Tiered6FeesAmex;
        pinDebit?: Payroc.PinDebit;
        electronicBenefitsTransfer?: Payroc.ElectronicBenefitsTransfer;
        specialityCards?: Payroc.SpecialityCards;
    }
}
