// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains the fees for American Express transactions.
 */
export type Tiered6FeesAmex = Payroc.Tiered6FeesAmex.OptBlue | Payroc.Tiered6FeesAmex.Direct;

export namespace Tiered6FeesAmex {
    export interface OptBlue extends Payroc.Tiered6AmexOptBlue {
        type: "optBlue";
    }

    export interface Direct extends Payroc.Tiered6AmexDirect {
        type: "direct";
    }
}
