// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about tiered pricing with four tiers.
 */
export interface Tiered4 {
    /** Object that contains information about the fees. */
    fees: Tiered4.Fees;
}

export namespace Tiered4 {
    /**
     * Object that contains information about the fees.
     */
    export interface Fees {
        /** Object that contains the fees for Mastercard, Visa, and Discover transactions. */
        mastercardVisaDiscover: Payroc.QualRatesWithPremium;
        /**
         * Polymorphic object that contains fees for American Express transactions.
         *
         * The value of the type field determines which variant you should use:
         * -	`optBlue` - Amex OptBlue pricing program.
         * -	`direct` - Amex Direct pricing program.
         */
        amex?: Payroc.Tiered4FeesAmex | undefined;
        pinDebit?: Payroc.PinDebit | undefined;
        electronicBenefitsTransfer?: Payroc.ElectronicBenefitsTransfer | undefined;
        specialityCards?: Payroc.SpecialityCards | undefined;
    }
}
