// This file was auto-generated by Fern from our API Definition.

/** Indicates who provides training to the merchant for the solution. */
export const TrainingProvider = {
    Partner: "partner",
    Payroc: "payroc",
} as const;
export type TrainingProvider = (typeof TrainingProvider)[keyof typeof TrainingProvider];
