// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../index.js";

/**
 * Object that contains information about the transaction.
 */
export interface Transaction {
    /** Unique identifier that we assigned to the transaction. */
    transactionId?: number;
    /**
     * Indicates the type of transaction. The value is one of the following:
     *
     * - `capture` - Transaction is a sale.
     * - `return` - Transaction is a refund.
     */
    type?: Transaction.Type;
    /** Date of the transaction. The format of this value is **YYYY-MM-DD**. */
    date?: string;
    /** Transaction amount. We return the value in the currency's lowest denomination, for example, cents. */
    amount?: number;
    /** Indicates how the merchant received the payment details. */
    entryMethod?: Transaction.EntryMethod;
    /** Date that we received the transaction.  The format of this value is **YYYY-MM-DD**. */
    createdDate?: string;
    /** Date that the transaction was last changed.  The format of this value is **YYYY-MM-DD**. */
    lastModifiedDate?: string;
    /**
     * Indicates the status of the transaction. The value is one of the following:
     *
     * -	`fullSuspense` – Merchant ran the transaction while their account was in full suspense.
     * -	`heldAudited` – We have moved a transaction from fullSuspense and placed it on hold.
     * -	`heldReleasedAudited` – We audited and released the transaction that we had previously held.
     * -	`holdForSettlement30Days` - We are holding the transaction for a maximum of 30 days.
     * -	`holdForSettlementDuplicate` - We held the transaction because the transaction may be a duplicate.
     * -	`holdLongTerm` - We are holding the transaction for an extended period.
     * -	`paid` – We have paid the transaction funds to the merchant.
     * -	`paidByThirdParty` - A third party has paid the transaction funds to the merchant.
     * -	`partialRelease` – We partially released the transaction funds.
     * -	`pull` - We pulled the transaction, and the merchant does not receive funds for the transaction.
     * -	`release` - We released the transaction that we previously held.
     * -	`new` – We have prepared the funds from the transaction to send to the merchant.
     * -	`held` – We held the transaction.
     * -	`unknown` – No transaction status available.
     */
    status?: Transaction.Status;
    /** Cashback amount. We return the value in the currency's lowest denomination, for example, cents. */
    cashbackAmount?: number;
    /** Object that contains information about the interchange fees for the transaction. */
    interchange?: Transaction.Interchange;
    /** Currency of the transaction. The value for the currency follows the [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) standard. */
    currency?: string;
    merchant?: Payroc.MerchantSummary;
    settled?: Payroc.SettledSummary;
    batch?: Payroc.BatchSummary;
    card?: Payroc.CardSummary;
    authorization?: Payroc.AuthorizationSummary;
}

export namespace Transaction {
    /**
     * Indicates the type of transaction. The value is one of the following:
     *
     * - `capture` - Transaction is a sale.
     * - `return` - Transaction is a refund.
     */
    export const Type = {
        Capture: "capture",
        Return: "return",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Indicates how the merchant received the payment details. */
    export const EntryMethod = {
        BarcodeRead: "barcodeRead",
        SmartChipRead: "smartChipRead",
        SwipedOriginUnknown: "swipedOriginUnknown",
        ContactlessChip: "contactlessChip",
        Ecommerce: "ecommerce",
        ManuallyEntered: "manuallyEntered",
        ManuallyEnteredFallback: "manuallyEnteredFallback",
        Swiped: "swiped",
        SwipedFallback: "swipedFallback",
        SwipedError: "swipedError",
        ScannedCheckReader: "scannedCheckReader",
        CredentialOnFile: "credentialOnFile",
        Unknown: "unknown",
    } as const;
    export type EntryMethod = (typeof EntryMethod)[keyof typeof EntryMethod];
    /**
     * Indicates the status of the transaction. The value is one of the following:
     *
     * -	`fullSuspense` – Merchant ran the transaction while their account was in full suspense.
     * -	`heldAudited` – We have moved a transaction from fullSuspense and placed it on hold.
     * -	`heldReleasedAudited` – We audited and released the transaction that we had previously held.
     * -	`holdForSettlement30Days` - We are holding the transaction for a maximum of 30 days.
     * -	`holdForSettlementDuplicate` - We held the transaction because the transaction may be a duplicate.
     * -	`holdLongTerm` - We are holding the transaction for an extended period.
     * -	`paid` – We have paid the transaction funds to the merchant.
     * -	`paidByThirdParty` - A third party has paid the transaction funds to the merchant.
     * -	`partialRelease` – We partially released the transaction funds.
     * -	`pull` - We pulled the transaction, and the merchant does not receive funds for the transaction.
     * -	`release` - We released the transaction that we previously held.
     * -	`new` – We have prepared the funds from the transaction to send to the merchant.
     * -	`held` – We held the transaction.
     * -	`unknown` – No transaction status available.
     */
    export const Status = {
        FullSuspense: "fullSuspense",
        HeldAudited: "heldAudited",
        HeldReleasedAudited: "heldReleasedAudited",
        HoldForSettlement30Days: "holdForSettlement30Days",
        HoldForSettlementDuplicate: "holdForSettlementDuplicate",
        HoldLongTerm: "holdLongTerm",
        Paid: "paid",
        PaidByThirdParty: "paidByThirdParty",
        PartialRelease: "partialRelease",
        Pull: "pull",
        Release: "release",
        New: "new",
        Held: "held",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * Object that contains information about the interchange fees for the transaction.
     */
    export interface Interchange {
        /** Interchange basis points that we apply to the transaction. */
        basisPoint?: number;
        /** Interchange fee for the transaction. We return the value in the currency's lowest denomination, for example, cents. */
        transactionFee?: number;
    }
}
