// This file was auto-generated by Fern from our API Definition.

/**
 * Object that contains information about the EBT voucher.
 *
 * **Note:** Vouchers are available only for EBT SNAP payments.
 */
export interface Voucher {
    /** Authorization code that the processor issued for the transaction. */
    approvalCode: string;
    /** Serial number of the voucher. */
    serialNumber: string;
}
