// This file was auto-generated by Fern from our API Definition.

import * as Payroc from "../../../src/api/index";
import { PayrocClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockBearer } from "../mockAuth";

describe("BankTransferRefundsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            limit: 2,
            count: 2,
            hasMore: true,
            links: [
                {
                    rel: "next",
                    method: "get",
                    href: "https://api.payroc.com/v1/bank-transfer-refunds?limit=2&processingTerminalId=1234001&after=B6ZOFZNVOP",
                },
                {
                    rel: "previous",
                    method: "get",
                    href: "https://api.payroc.com/v1/bank-transfer-refunds?processingTerminalId=1234001&limit=2&before=CD3HN88U9F",
                },
            ],
            data: [
                {
                    refundId: "CD3HN88U9F",
                    processingTerminalId: "1234001",
                    order: {
                        orderId: "OrderRef6543",
                        dateTime: "2024-07-02T15:30:00Z",
                        description: "refund example",
                        amount: 4999,
                        currency: "USD",
                    },
                    customer: {
                        notificationLanguage: "en",
                        contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
                    },
                    bankAccount: {
                        type: "ach",
                        nameOnAccount: "Sarah Hazel Hopper",
                        accountNumber: "123456789",
                        routingNumber: "123456789",
                        secureToken: {
                            secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                            customerName: "Sarah Hazel Hopper",
                            token: "296753123456",
                            status: "notValidated",
                            link: { rel: "previous", method: "get", href: "<uri>" },
                        },
                    },
                    payment: {
                        paymentId: "M2MJOG6O2Y",
                        dateTime: "2024-07-02T15:30:00Z",
                        currency: "AED",
                        amount: 4999,
                        status: "ready",
                        responseCode: "A",
                        responseMessage: "Transaction approved",
                        link: { rel: "previous", method: "get", href: "<uri>" },
                    },
                    transactionResult: {
                        type: "unreferencedRefund",
                        status: "ready",
                        authorizedAmount: -4999,
                        currency: "USD",
                        responseCode: "A",
                        responseMessage: "NoError",
                        processorResponseCode: "0",
                    },
                    customFields: [{ name: "yourCustomField", value: "abc123" }],
                },
                {
                    refundId: "B6ZOFZNVOP",
                    processingTerminalId: "1234001",
                    order: {
                        orderId: "OrderRef7654",
                        dateTime: "2024-07-02T15:30:00Z",
                        description: "Refund for order OrderRef7654",
                        amount: 3999,
                        currency: "USD",
                    },
                    customer: {
                        notificationLanguage: "en",
                        contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
                    },
                    bankAccount: {
                        type: "ach",
                        nameOnAccount: "Sarah Hazel Hopper",
                        accountNumber: "123456789",
                        routingNumber: "123456789",
                        secureToken: {
                            secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                            customerName: "Sarah Hazel Hopper",
                            token: "296753123456",
                            status: "notValidated",
                            link: { rel: "previous", method: "get", href: "<uri>" },
                        },
                    },
                    payment: {
                        paymentId: "M2MJOG6O2Y",
                        dateTime: "2024-07-02T15:30:00Z",
                        currency: "AED",
                        amount: 4999,
                        status: "ready",
                        responseCode: "A",
                        responseMessage: "Transaction approved",
                        link: { rel: "previous", method: "get", href: "<uri>" },
                    },
                    transactionResult: {
                        type: "unreferencedRefund",
                        status: "ready",
                        authorizedAmount: -3999,
                        currency: "USD",
                        responseCode: "A",
                        responseMessage: "NoError",
                        processorResponseCode: "0",
                    },
                    customFields: [{ name: "yourCustomField", value: "abc123" }],
                },
            ],
        };
        server
            .mockEndpoint({ once: false })
            .get("/bank-transfer-refunds")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            limit: 2,
            count: 2,
            hasMore: true,
            links: [
                {
                    rel: "next",
                    method: "get",
                    href: "https://api.payroc.com/v1/bank-transfer-refunds?limit=2&processingTerminalId=1234001&after=B6ZOFZNVOP",
                },
                {
                    rel: "previous",
                    method: "get",
                    href: "https://api.payroc.com/v1/bank-transfer-refunds?processingTerminalId=1234001&limit=2&before=CD3HN88U9F",
                },
            ],
            data: [
                {
                    refundId: "CD3HN88U9F",
                    processingTerminalId: "1234001",
                    order: {
                        orderId: "OrderRef6543",
                        dateTime: "2024-07-02T15:30:00Z",
                        description: "refund example",
                        amount: 4999,
                        currency: "USD",
                    },
                    customer: {
                        notificationLanguage: "en",
                        contactMethods: [
                            {
                                type: "email",
                                value: "jane.doe@example.com",
                            },
                        ],
                    },
                    bankAccount: {
                        type: "ach",
                        nameOnAccount: "Sarah Hazel Hopper",
                        accountNumber: "123456789",
                        routingNumber: "123456789",
                        secureToken: {
                            secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                            customerName: "Sarah Hazel Hopper",
                            token: "296753123456",
                            status: "notValidated",
                            link: {
                                rel: "previous",
                                method: "get",
                                href: "<uri>",
                            },
                        },
                    },
                    payment: {
                        paymentId: "M2MJOG6O2Y",
                        dateTime: "2024-07-02T15:30:00Z",
                        currency: "AED",
                        amount: 4999,
                        status: "ready",
                        responseCode: "A",
                        responseMessage: "Transaction approved",
                        link: {
                            rel: "previous",
                            method: "get",
                            href: "<uri>",
                        },
                    },
                    transactionResult: {
                        type: "unreferencedRefund",
                        status: "ready",
                        authorizedAmount: -4999,
                        currency: "USD",
                        responseCode: "A",
                        responseMessage: "NoError",
                        processorResponseCode: "0",
                    },
                    customFields: [
                        {
                            name: "yourCustomField",
                            value: "abc123",
                        },
                    ],
                },
                {
                    refundId: "B6ZOFZNVOP",
                    processingTerminalId: "1234001",
                    order: {
                        orderId: "OrderRef7654",
                        dateTime: "2024-07-02T15:30:00Z",
                        description: "Refund for order OrderRef7654",
                        amount: 3999,
                        currency: "USD",
                    },
                    customer: {
                        notificationLanguage: "en",
                        contactMethods: [
                            {
                                type: "email",
                                value: "jane.doe@example.com",
                            },
                        ],
                    },
                    bankAccount: {
                        type: "ach",
                        nameOnAccount: "Sarah Hazel Hopper",
                        accountNumber: "123456789",
                        routingNumber: "123456789",
                        secureToken: {
                            secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                            customerName: "Sarah Hazel Hopper",
                            token: "296753123456",
                            status: "notValidated",
                            link: {
                                rel: "previous",
                                method: "get",
                                href: "<uri>",
                            },
                        },
                    },
                    payment: {
                        paymentId: "M2MJOG6O2Y",
                        dateTime: "2024-07-02T15:30:00Z",
                        currency: "AED",
                        amount: 4999,
                        status: "ready",
                        responseCode: "A",
                        responseMessage: "Transaction approved",
                        link: {
                            rel: "previous",
                            method: "get",
                            href: "<uri>",
                        },
                    },
                    transactionResult: {
                        type: "unreferencedRefund",
                        status: "ready",
                        authorizedAmount: -3999,
                        currency: "USD",
                        responseCode: "A",
                        responseMessage: "NoError",
                        processorResponseCode: "0",
                    },
                    customFields: [
                        {
                            name: "yourCustomField",
                            value: "abc123",
                        },
                    ],
                },
            ],
        };
        const page = await client.payments.bankTransferRefunds.list({
            processingTerminalId: "1234001",
            orderId: "OrderRef6543",
            nameOnAccount: "Sarah%20Hazel%20Hopper",
            last4: "7062",
            dateFrom: "2024-07-01T00:00:00Z",
            dateTo: "2024-07-31T23:59:59Z",
            settlementState: "settled",
            settlementDate: "2024-07-15",
            before: "2571",
            after: "8516",
            limit: 1,
        });
        expect(expected.data).toEqual(page.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            limit: 10,
            count: 0,
            hasMore: false,
            links: [
                { rel: "previous", method: "get", href: "<uri>" },
                { rel: "next", method: "get", href: "<uri>" },
            ],
        };
        server
            .mockEndpoint({ once: false })
            .get("/bank-transfer-refunds")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const page = await client.payments.bankTransferRefunds.list({
            processingTerminalId: "1234001",
            orderId: "OrderRef6543",
            nameOnAccount: "Sarah%20Hazel%20Hopper",
            last4: "7062",
            dateFrom: "2024-07-01T00:00:00Z",
            dateTo: "2024-07-31T23:59:59Z",
            settlementState: "settled",
            settlementDate: "2024-07-15",
            before: "2571",
            after: "8516",
            limit: 1,
        });
        expect(page.data).toEqual([]);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint({ once: false })
            .get("/bank-transfer-refunds")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.list({
                processingTerminalId: "buzz",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint({ once: false })
            .get("/bank-transfer-refunds")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.list({
                processingTerminalId: "buzz",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint({ once: false })
            .get("/bank-transfer-refunds")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.list({
                processingTerminalId: "buzz",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint({ once: false })
            .get("/bank-transfer-refunds")
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.list({
                processingTerminalId: "buzz",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint({ once: false })
            .get("/bank-transfer-refunds")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.list({
                processingTerminalId: "buzz",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            refundMethod: {
                type: "ach",
                nameOnAccount: "Shara Hazel Hopper",
                accountNumber: "1234567890",
                routingNumber: "123456789",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        const rawResponseBody = {
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.bankTransferRefunds.create({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            refundMethod: {
                type: "ach",
                nameOnAccount: "Shara Hazel Hopper",
                accountNumber: "1234567890",
                routingNumber: "123456789",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
        expect(response).toEqual({
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/CD3HN88U9F")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.bankTransferRefunds.retrieve({
            refundId: "CD3HN88U9F",
        });
        expect(response).toEqual({
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("reverse (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "reversal",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/CD3HN88U9F/reverse")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.bankTransferRefunds.reverse({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            refundId: "CD3HN88U9F",
        });
        expect(response).toEqual({
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "reversal",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("reverse (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("reverse (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("reverse (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("reverse (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("reverse (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("reverse (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("reverse (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("reverse (9)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.bankTransferRefunds.reverse({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });
});
