// This file was auto-generated by Fern from our API Definition.

import * as Payroc from "../../../src/api/index";
import { PayrocClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockBearer } from "../mockAuth";

describe("HostedFieldsClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "1.1.0.123456", scenario: "payment" };
        const rawResponseBody = {
            processingTerminalId: "1234001",
            token: "abcdef1234567890abcdef1234567890",
            expiresAt: "2025-07-02T13:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/processing-terminals/1234001/hosted-fields-sessions")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.hostedFields.create({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            processingTerminalId: "1234001",
            libVersion: "1.1.0.123456",
            scenario: "payment",
        });
        expect(response).toEqual({
            processingTerminalId: "1234001",
            token: "abcdef1234567890abcdef1234567890",
            expiresAt: "2025-07-02T13:30:00Z",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "libVersion", scenario: "payment" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/processing-terminals/processingTerminalId/hosted-fields-sessions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.hostedFields.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "processingTerminalId",
                libVersion: "libVersion",
                scenario: "payment",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "libVersion", scenario: "payment" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/processing-terminals/processingTerminalId/hosted-fields-sessions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.hostedFields.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "processingTerminalId",
                libVersion: "libVersion",
                scenario: "payment",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "libVersion", scenario: "payment" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/processing-terminals/processingTerminalId/hosted-fields-sessions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.hostedFields.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "processingTerminalId",
                libVersion: "libVersion",
                scenario: "payment",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "libVersion", scenario: "payment" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/processing-terminals/processingTerminalId/hosted-fields-sessions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.hostedFields.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "processingTerminalId",
                libVersion: "libVersion",
                scenario: "payment",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "libVersion", scenario: "payment" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/processing-terminals/processingTerminalId/hosted-fields-sessions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.hostedFields.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "processingTerminalId",
                libVersion: "libVersion",
                scenario: "payment",
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "libVersion", scenario: "payment" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/processing-terminals/processingTerminalId/hosted-fields-sessions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.hostedFields.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "processingTerminalId",
                libVersion: "libVersion",
                scenario: "payment",
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { libVersion: "libVersion", scenario: "payment" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/processing-terminals/processingTerminalId/hosted-fields-sessions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.hostedFields.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "processingTerminalId",
                libVersion: "libVersion",
                scenario: "payment",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });
});
