// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         processingTerminalId: "1234001",
 *         orderId: "OrderRef6543",
 *         nameOnAccount: "Sarah%20Hazel%20Hopper",
 *         last4: "7062",
 *         dateFrom: "2024-07-01T00:00:00Z",
 *         dateTo: "2024-07-31T23:59:59Z",
 *         settlementState: "settled",
 *         settlementDate: "2024-07-15",
 *         before: "2571",
 *         after: "8516",
 *         limit: 1
 *     }
 *
 * @example
 *     {
 *         processingTerminalId: "1234001",
 *         orderId: "OrderRef6543",
 *         nameOnAccount: "Sarah%20Hazel%20Hopper",
 *         last4: "7062",
 *         dateFrom: "2024-07-01T00:00:00Z",
 *         dateTo: "2024-07-31T23:59:59Z",
 *         settlementState: "settled",
 *         settlementDate: "2024-07-15",
 *         before: "2571",
 *         after: "8516",
 *         limit: 1
 *     }
 */
export interface ListBankTransferRefundsRequest {
    /** Filter results by the unique identifier that we assigned to the terminal. */
    processingTerminalId: string;
    /** Filter results by the order ID of the refund. */
    orderId?: string;
    /** Filter results by the accountholder's name. */
    nameOnAccount?: string;
    /** Filter results by the last four digits of the account number. */
    last4?: string;
    /** Filter results by transaction type. */
    type?:
        | Payroc.payments.ListBankTransferRefundsRequestTypeItem
        | Payroc.payments.ListBankTransferRefundsRequestTypeItem[];
    /** Filter results by the status of the refund. */
    status?:
        | Payroc.payments.ListBankTransferRefundsRequestStatusItem
        | Payroc.payments.ListBankTransferRefundsRequestStatusItem[];
    /** Filter results by refunds that the merchant ran after a specific date. The value follows the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard. */
    dateFrom?: string;
    /** Filter results by refunds that the merchant ran before a specific date. The value follows the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard. */
    dateTo?: string;
    /** Filter results by the settlement status. */
    settlementState?: Payroc.payments.ListBankTransferRefundsRequestSettlementState;
    /** Filter results by the settlement date. Send a value in **YYYY-MM-DD** format. */
    settlementDate?: string;
    /**
     * Return the previous page of results before the value that you specify.
     *
     * You can’t send the before parameter in the same request as the after parameter.
     */
    before?: string;
    /**
     * Return the next page of results after the value that you specify.
     *
     * You can’t send the after parameter in the same request as the before parameter.
     */
    after?: string;
    /** Limit the maximum number of results that we return for each page. */
    limit?: number;
}
