// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../index.js";

/**
 * Object that contains information about the card.
 */
export type BalanceInquiryCard =
    | Payroc.paymentFeatures.BalanceInquiryCard.Card
    | Payroc.paymentFeatures.BalanceInquiryCard.SingleUseToken;

export namespace BalanceInquiryCard {
    export interface Card extends Payroc.CardPayload {
        type: "card";
    }

    export interface SingleUseToken extends Payroc.SingleUseTokenPayload {
        type: "singleUseToken";
    }
}
