// This file was auto-generated by Fern from our API Definition.

export const ListPaymentLinksRequestStatus = {
    Active: "active",
    Completed: "completed",
    Deactivated: "deactivated",
    Expired: "expired",
} as const;
export type ListPaymentLinksRequestStatus =
    (typeof ListPaymentLinksRequestStatus)[keyof typeof ListPaymentLinksRequestStatus];
