// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         instructionId: 1
 *     }
 */
export interface RetrieveFundingInstructionsRequest {
    /** Unique identifier that we assigned to the funding instruction. */
    instructionId: number;
}
