// This file was auto-generated by Fern from our API Definition.

/** Filter terminal orders by status. */
export const ListTerminalOrdersProcessingAccountsRequestStatus = {
    Open: "open",
    Held: "held",
    Dispatched: "dispatched",
    Fulfilled: "fulfilled",
    Cancelled: "cancelled",
} as const;
export type ListTerminalOrdersProcessingAccountsRequestStatus =
    (typeof ListTerminalOrdersProcessingAccountsRequestStatus)[keyof typeof ListTerminalOrdersProcessingAccountsRequestStatus];
