// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
 *         recipientId: 1,
 *         body: {
 *             firstName: "Jane",
 *             lastName: "Doe",
 *             dateOfBirth: "1964-03-22",
 *             address: {
 *                 address1: "1 Example Ave.",
 *                 city: "Chicago",
 *                 state: "Illinois",
 *                 country: "US",
 *                 postalCode: "60056"
 *             },
 *             identifiers: [{
 *                     type: "nationalId",
 *                     value: "xxxxx4320"
 *                 }],
 *             contactMethods: [{
 *                     type: "email",
 *                     value: "jane.doe@example.com"
 *                 }],
 *             relationship: {
 *                 isControlProng: true
 *             }
 *         }
 *     }
 */
export interface CreateOwnerFundingRecipientsRequest {
    /** Unique identifier that we assigned to the funding recipient. */
    recipientId: number;
    /** Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency). */
    "Idempotency-Key": string;
    body: Payroc.Owner;
}
