// This file was auto-generated by Fern from our API Definition.

export interface RetrieveSignaturesResponse {
    /** Unique identifier that we assigned to the signature. */
    signatureId?: string | undefined;
    /** Unique identifier of the terminal that the signature is linked to. */
    processingTerminalId?: string | undefined;
    /** Date that the device captured the signature. The format of this value is **YYYY-MM-DD**. */
    createdOn?: string | undefined;
    /** MIME type that indicates the format of the image file. */
    contentType?: string | undefined;
    /** Image data for the signature. Our gateway returns the signature as a Base64-encoded value. */
    signature?: string | undefined;
}
