// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Payroc from "../../../../../index.js";

export declare namespace FundingInstructionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FundingInstructionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FundingInstructionsClient.Options>;

    constructor(options: FundingInstructionsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * > Important: You can return a list of funding instructions from only the previous two years. If you want to view a funding instruction from more than two years ago and you have its instructionId, use our [Retrieve Funding Instruction](https://docs.payroc.com/api/schema/funding/funding-instructions/retrieve) method.
     *
     * Use this method to return a [paginated](https://docs.payroc.com/api/pagination) list of funding instructions within a specific date range.
     *
     * **Note:** If you want to view the details of a specific funding instruction and you have its instructionId, use our [Retrieve Funding Instruction](https://docs.payroc.com/api/schema/funding/funding-instructions/retrieve) method.
     *
     * Our gateway returns the following information for each instruction in the list:
     * -	Status of the funding instruction.
     * -	Funding information, including which merchant's funding balance we distribute and the funding account that we send the balance to.
     *
     * For each funding instruction, we also return the instructionId, which you can use to perform follow-on actions.
     *
     * @param {Payroc.funding.ListFundingInstructionsRequest} request
     * @param {FundingInstructionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payroc.BadRequestError}
     * @throws {@link Payroc.UnauthorizedError}
     * @throws {@link Payroc.ForbiddenError}
     * @throws {@link Payroc.NotAcceptableError}
     * @throws {@link Payroc.InternalServerError}
     *
     * @example
     *     await client.funding.fundingInstructions.list({
     *         before: "2571",
     *         after: "8516",
     *         limit: 1,
     *         dateFrom: "2024-07-01",
     *         dateTo: "2024-07-03"
     *     })
     */
    public async list(
        request: Payroc.funding.ListFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): Promise<
        core.PayrocPager<
            Payroc.funding.ListFundingInstructionsResponse.Data.Item,
            Payroc.funding.ListFundingInstructionsRequest,
            Payroc.funding.ListFundingInstructionsResponse
        >
    > {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Payroc.funding.ListFundingInstructionsRequest,
            ): Promise<core.WithRawResponse<Payroc.funding.ListFundingInstructionsResponse>> => {
                const { before, after, limit, dateFrom, dateTo } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (before != null) {
                    _queryParams.before = before;
                }
                if (after != null) {
                    _queryParams.after = after;
                }
                if (limit != null) {
                    _queryParams.limit = limit.toString();
                }
                _queryParams.dateFrom = dateFrom;
                _queryParams.dateTo = dateTo;
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (
                                (await core.Supplier.get(this._options.environment)) ??
                                environments.PayrocEnvironment.Production
                            ).api,
                        "funding-instructions",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Payroc.funding.ListFundingInstructionsResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Payroc.BadRequestError(
                                _response.error.body as Payroc.FourHundred,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Payroc.UnauthorizedError(
                                _response.error.body as Payroc.FourHundredOne,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Payroc.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 406:
                            throw new Payroc.NotAcceptableError(
                                _response.error.body as Payroc.FourHundredSix,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Payroc.InternalServerError(
                                _response.error.body as Payroc.FiveHundred,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.PayrocError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/funding-instructions");
            },
        );
        return core.PayrocPager.create<
            Payroc.funding.ListFundingInstructionsResponse.Data.Item,
            Payroc.funding.ListFundingInstructionsRequest,
            Payroc.funding.ListFundingInstructionsResponse
        >({
            sendRequest: list,
            initialRequest: request,
            parse: async (
                _request: Payroc.funding.ListFundingInstructionsRequest,
                response: core.WithRawResponse<Payroc.funding.ListFundingInstructionsResponse>,
            ) => ({
                hasNextPage: false,
                hasPreviousPage: false,
                items: ((response) => response?.data ?? [])(response.data),
            }),
        });
    }

    /**
     * Use this method to create a funding instruction that tells us how to distribute the funds from your merchants' transactions.
     *
     * **Note:** Before you create a funding instruction, you can use our [List Funding Balances](https://docs.payroc.com/api/schema/funding/funding-activity/retrieve-balance) method to view the amount of available funds that a merchant has.
     *
     * In your request, include an array of merchantInstruction objects. Each merchantInstruction object contains the following:
     * -	Merchant ID (MID) of the merchant whose funding balance you want to distribute.
     * -	Funding account that you want to send funds to.
     * -	Amount that you want to send to the funding account.
     *
     * Our gateway returns the instructionId, which you can use to run follow-on actions.
     *
     * @param {Payroc.funding.CreateFundingInstructionsRequest} request
     * @param {FundingInstructionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payroc.BadRequestError}
     * @throws {@link Payroc.UnauthorizedError}
     * @throws {@link Payroc.ForbiddenError}
     * @throws {@link Payroc.NotAcceptableError}
     * @throws {@link Payroc.ConflictError}
     * @throws {@link Payroc.InternalServerError}
     *
     * @example
     *     await client.funding.fundingInstructions.create({
     *         "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
     *         body: {}
     *     })
     */
    public create(
        request: Payroc.funding.CreateFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): core.HttpResponsePromise<Payroc.Instruction> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Payroc.funding.CreateFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payroc.Instruction>> {
        const { "Idempotency-Key": idempotencyKey, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.PayrocEnvironment.Production)
                        .api,
                "funding-instructions",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payroc.Instruction, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payroc.BadRequestError(_response.error.body as Payroc.FourHundred, _response.rawResponse);
                case 401:
                    throw new Payroc.UnauthorizedError(
                        _response.error.body as Payroc.FourHundredOne,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Payroc.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 406:
                    throw new Payroc.NotAcceptableError(
                        _response.error.body as Payroc.FourHundredSix,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Payroc.ConflictError(
                        _response.error.body as Payroc.FourHundredNine,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Payroc.InternalServerError(
                        _response.error.body as Payroc.FiveHundred,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayrocError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/funding-instructions");
    }

    /**
     * Use this method to retrieve information about a funding instruction.
     *
     * To retrieve a funding instruction, you need its instructionId. Our gateway returned the instructionId in the response of the [Create Funding Instruction](https://docs.payroc.com/api/schema/funding/funding-instructions/create) method.
     *
     * **Note:** If you don't have the instructionId, use our [List Funding Instructions](https://docs.payroc.com/api/schema/funding/funding-instructions/list) method to search for the funding instruction.
     *
     * Our gateway returns the following information about the funding instruction:
     * -	Status of the funding instruction.
     * -	Funding information, including which merchant's funding balance we distribute and the funding account that we send the balance to.
     *
     * @param {Payroc.funding.RetrieveFundingInstructionsRequest} request
     * @param {FundingInstructionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payroc.BadRequestError}
     * @throws {@link Payroc.UnauthorizedError}
     * @throws {@link Payroc.ForbiddenError}
     * @throws {@link Payroc.NotFoundError}
     * @throws {@link Payroc.NotAcceptableError}
     * @throws {@link Payroc.InternalServerError}
     *
     * @example
     *     await client.funding.fundingInstructions.retrieve({
     *         instructionId: 1
     *     })
     */
    public retrieve(
        request: Payroc.funding.RetrieveFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): core.HttpResponsePromise<Payroc.Instruction> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Payroc.funding.RetrieveFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Payroc.Instruction>> {
        const { instructionId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.PayrocEnvironment.Production)
                        .api,
                `funding-instructions/${core.url.encodePathParam(instructionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Payroc.Instruction, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payroc.BadRequestError(_response.error.body as Payroc.FourHundred, _response.rawResponse);
                case 401:
                    throw new Payroc.UnauthorizedError(
                        _response.error.body as Payroc.FourHundredOne,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Payroc.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Payroc.NotFoundError(
                        _response.error.body as Payroc.FourHundredFour,
                        _response.rawResponse,
                    );
                case 406:
                    throw new Payroc.NotAcceptableError(
                        _response.error.body as Payroc.FourHundredSix,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Payroc.InternalServerError(
                        _response.error.body as Payroc.FiveHundred,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayrocError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/funding-instructions/{instructionId}",
        );
    }

    /**
     * > **Important:** You can update a funding instruction only if its status is `accepted`. To view the status of a funding instruction, use our [Retrieve Funding Instruction](https://docs.payroc.com/api/schema/funding/funding-instructions/retrieve) method.
     *
     * Use this method to update the details of a funding instruction.
     *
     * To update a funding instruction, you need its instructionId. Our gateway returned the instructionId in the response of the [Create Funding Instruction](https://docs.payroc.com/api/schema/funding/funding-instructions/create) method.
     *
     * **Note:** If you don't have the fundingInstructionId, use our [List Funding Instructions](https://docs.payroc.com/api/schema/funding/funding-instructions/list) method to search for the funding instruction.
     *
     * You can modify the following information for the funding instruction:
     * -	Merchant ID (MID) of the merchant whose funding balance you want to distribute.
     * -	Funding account that you want to send funds to.
     * -	Amount that you want to send to the funding account.
     *
     * @param {Payroc.funding.UpdateFundingInstructionsRequest} request
     * @param {FundingInstructionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payroc.BadRequestError}
     * @throws {@link Payroc.UnauthorizedError}
     * @throws {@link Payroc.ForbiddenError}
     * @throws {@link Payroc.NotFoundError}
     * @throws {@link Payroc.InternalServerError}
     *
     * @example
     *     await client.funding.fundingInstructions.update({
     *         instructionId: 1,
     *         body: {}
     *     })
     */
    public update(
        request: Payroc.funding.UpdateFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Payroc.funding.UpdateFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { instructionId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.PayrocEnvironment.Production)
                        .api,
                `funding-instructions/${core.url.encodePathParam(instructionId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payroc.BadRequestError(_response.error.body as Payroc.FourHundred, _response.rawResponse);
                case 401:
                    throw new Payroc.UnauthorizedError(
                        _response.error.body as Payroc.FourHundredOne,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Payroc.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Payroc.NotFoundError(
                        _response.error.body as Payroc.FourHundredFour,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Payroc.InternalServerError(
                        _response.error.body as Payroc.FiveHundred,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayrocError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/funding-instructions/{instructionId}",
        );
    }

    /**
     * > **Important:** You can delete a funding instruction only if its status is `accepted`. To view the status of a funding instruction, use our [Retrieve Funding Instruction](https://docs.payroc.com/api/schema/funding/funding-instructions/retrieve) method.
     *
     * Use this method to delete a funding instruction.
     *
     * To delete a funding instruction, you need its instructionId. Our gateway returned the instructionId in the response of the [Create Funding Instruction](https://docs.payroc.com/api/schema/funding/funding-instructions/create) method.
     *
     * **Note:** If you don't have the instructionId, use our [List Funding Instructions](https://docs.payroc.com/api/schema/funding/funding-instructions/list) method to search for the funding instruction.
     *
     * @param {Payroc.funding.DeleteFundingInstructionsRequest} request
     * @param {FundingInstructionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Payroc.BadRequestError}
     * @throws {@link Payroc.UnauthorizedError}
     * @throws {@link Payroc.ForbiddenError}
     * @throws {@link Payroc.NotFoundError}
     * @throws {@link Payroc.InternalServerError}
     *
     * @example
     *     await client.funding.fundingInstructions.delete({
     *         instructionId: 1
     *     })
     */
    public delete(
        request: Payroc.funding.DeleteFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Payroc.funding.DeleteFundingInstructionsRequest,
        requestOptions?: FundingInstructionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { instructionId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.PayrocEnvironment.Production)
                        .api,
                `funding-instructions/${core.url.encodePathParam(instructionId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Payroc.BadRequestError(_response.error.body as Payroc.FourHundred, _response.rawResponse);
                case 401:
                    throw new Payroc.UnauthorizedError(
                        _response.error.body as Payroc.FourHundredOne,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Payroc.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Payroc.NotFoundError(
                        _response.error.body as Payroc.FourHundredFour,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Payroc.InternalServerError(
                        _response.error.body as Payroc.FiveHundred,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PayrocError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/funding-instructions/{instructionId}",
        );
    }
}
