// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         pricingIntentId: "5",
 *         body: {
 *             country: "US",
 *             version: "5.0",
 *             base: {
 *                 addressVerification: 5,
 *                 annualFee: {
 *                     billInMonth: "june",
 *                     amount: 9900
 *                 },
 *                 regulatoryAssistanceProgram: 15,
 *                 pciNonCompliance: 4995,
 *                 merchantAdvantage: 10,
 *                 platinumSecurity: {
 *                     billingFrequency: "monthly"
 *                 },
 *                 maintenance: 500,
 *                 minimum: 100,
 *                 voiceAuthorization: 95,
 *                 chargeback: 2500,
 *                 retrieval: 1500,
 *                 batch: 1500,
 *                 earlyTermination: 57500
 *             },
 *             processor: {
 *                 card: {
 *                     planType: "interchangePlus",
 *                     fees: {
 *                         mastercardVisaDiscover: {}
 *                     }
 *                 },
 *                 ach: {
 *                     fees: {
 *                         transaction: 50,
 *                         batch: 5,
 *                         returns: 400,
 *                         unauthorizedReturn: 1999,
 *                         statement: 800,
 *                         monthlyMinimum: 20000,
 *                         accountVerification: 10,
 *                         discountRateUnder10000: 5.25,
 *                         discountRateAbove10000: 10
 *                     }
 *                 }
 *             },
 *             gateway: {
 *                 fees: {
 *                     monthly: 2000,
 *                     setup: 5000,
 *                     perTransaction: 2000,
 *                     perDeviceMonthly: 10
 *                 }
 *             },
 *             services: [{
 *                     name: "hardwareAdvantagePlan",
 *                     enabled: true
 *                 }],
 *             key: "Your-Unique-Identifier",
 *             metadata: {
 *                 "yourCustomField": "abc123"
 *             }
 *         }
 *     }
 */
export interface UpdatePricingIntentsRequest {
    /** Unique identifier that we assigned to the pricing intent. */
    pricingIntentId: string;
    body: Payroc.PricingIntent;
}
