// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../index.js";

/**
 * Polymorphic object that contains payment details for the refund.
 *
 * The value of the type parameter determines which variant you should use:
 * -	`ach` - Automated Clearing House (ACH) details
 * -	`secureToken` - Secure token details
 */
export type BankTransferUnreferencedRefundRefundMethod =
    | Payroc.bankTransferPayments.BankTransferUnreferencedRefundRefundMethod.Ach
    | Payroc.bankTransferPayments.BankTransferUnreferencedRefundRefundMethod.SecureToken;

export namespace BankTransferUnreferencedRefundRefundMethod {
    export interface Ach extends Payroc.AchPayload {
        type: "ach";
    }

    export interface SecureToken extends Payroc.SecureTokenPayload {
        type: "secureToken";
    }
}
