// This file was auto-generated by Fern from our API Definition.

export const ListRefundsRequestStatusItem = {
    Ready: "ready",
    Pending: "pending",
    Declined: "declined",
    Complete: "complete",
    Admin: "admin",
    Reversal: "reversal",
    Returned: "returned",
} as const;
export type ListRefundsRequestStatusItem =
    (typeof ListRefundsRequestStatusItem)[keyof typeof ListRefundsRequestStatusItem];
