// This file was auto-generated by Fern from our API Definition.

export const ListBankTransferPaymentsRequestTypeItem = {
    Payment: "payment",
    AccountVerification: "accountVerification",
} as const;
export type ListBankTransferPaymentsRequestTypeItem =
    (typeof ListBankTransferPaymentsRequestTypeItem)[keyof typeof ListBankTransferPaymentsRequestTypeItem];
