// This file was auto-generated by Fern from our API Definition.

import * as Payroc from "../../../src/api/index";
import { PayrocClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockBearer } from "../mockAuth";

describe("OwnersClient", () => {
    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            ownerId: 4564,
            firstName: "Jane",
            middleName: "Helen",
            lastName: "Doe",
            dateOfBirth: "1964-03-22",
            address: {
                address1: "1 Example Ave.",
                address2: "Example Address Line 2",
                address3: "Example Address Line 3",
                city: "Chicago",
                state: "Illinois",
                country: "US",
                postalCode: "60056",
            },
            identifiers: [{ type: "nationalId", value: "xxxxx4320" }],
            contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            relationship: { equityPercentage: 48.5, title: "CFO", isControlProng: true, isAuthorizedSignatory: false },
        };
        server.mockEndpoint().get("/owners/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.boarding.owners.retrieve({
            ownerId: 1,
        });
        expect(response).toEqual({
            ownerId: 4564,
            firstName: "Jane",
            middleName: "Helen",
            lastName: "Doe",
            dateOfBirth: "1964-03-22",
            address: {
                address1: "1 Example Ave.",
                address2: "Example Address Line 2",
                address3: "Example Address Line 3",
                city: "Chicago",
                state: "Illinois",
                country: "US",
                postalCode: "60056",
            },
            identifiers: [
                {
                    type: "nationalId",
                    value: "xxxxx4320",
                },
            ],
            contactMethods: [
                {
                    type: "email",
                    value: "jane.doe@example.com",
                },
            ],
            relationship: {
                equityPercentage: 48.5,
                title: "CFO",
                isControlProng: true,
                isAuthorizedSignatory: false,
            },
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().get("/owners/1").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.retrieve({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().get("/owners/1").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.retrieve({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/owners/1").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.retrieve({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().get("/owners/1").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.retrieve({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().get("/owners/1").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.retrieve({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            firstName: "Jane",
            middleName: "Helen",
            lastName: "Doe",
            dateOfBirth: "1964-03-22",
            address: {
                address1: "1 Example Ave.",
                address2: "Example Address Line 2",
                address3: "Example Address Line 3",
                city: "Chicago",
                state: "Illinois",
                country: "US",
                postalCode: "60056",
            },
            identifiers: [{ type: "nationalId", value: "000-00-4320" }],
            contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            relationship: { equityPercentage: 48.5, title: "CFO", isControlProng: true, isAuthorizedSignatory: false },
        };

        server.mockEndpoint().put("/owners/1").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.boarding.owners.update({
            ownerId: 1,
            body: {
                firstName: "Jane",
                middleName: "Helen",
                lastName: "Doe",
                dateOfBirth: "1964-03-22",
                address: {
                    address1: "1 Example Ave.",
                    address2: "Example Address Line 2",
                    address3: "Example Address Line 3",
                    city: "Chicago",
                    state: "Illinois",
                    country: "US",
                    postalCode: "60056",
                },
                identifiers: [
                    {
                        type: "nationalId",
                        value: "000-00-4320",
                    },
                ],
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
                relationship: {
                    equityPercentage: 48.5,
                    title: "CFO",
                    isControlProng: true,
                    isAuthorizedSignatory: false,
                },
            },
        });
        expect(response).toEqual(undefined);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2023-01-15",
            address: { address1: "address1", city: "city", state: "state", country: "xy", postalCode: "postalCode" },
            identifiers: [
                { type: "nationalId", value: "value" },
                { type: "nationalId", value: "value" },
            ],
            contactMethods: [
                { type: "email", value: "value" },
                { type: "email", value: "value" },
            ],
            relationship: { isControlProng: true },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .put("/owners/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.owners.update({
                ownerId: 1,
                body: {
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2023-01-15",
                    address: {
                        address1: "address1",
                        city: "city",
                        state: "state",
                        country: "xy",
                        postalCode: "postalCode",
                    },
                    identifiers: [
                        {
                            type: "nationalId",
                            value: "value",
                        },
                        {
                            type: "nationalId",
                            value: "value",
                        },
                    ],
                    contactMethods: [
                        {
                            type: "email",
                            value: "value",
                        },
                        {
                            type: "email",
                            value: "value",
                        },
                    ],
                    relationship: {
                        isControlProng: true,
                    },
                },
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2023-01-15",
            address: { address1: "address1", city: "city", state: "state", country: "xy", postalCode: "postalCode" },
            identifiers: [
                { type: "nationalId", value: "value" },
                { type: "nationalId", value: "value" },
            ],
            contactMethods: [
                { type: "email", value: "value" },
                { type: "email", value: "value" },
            ],
            relationship: { isControlProng: true },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .put("/owners/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.owners.update({
                ownerId: 1,
                body: {
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2023-01-15",
                    address: {
                        address1: "address1",
                        city: "city",
                        state: "state",
                        country: "xy",
                        postalCode: "postalCode",
                    },
                    identifiers: [
                        {
                            type: "nationalId",
                            value: "value",
                        },
                        {
                            type: "nationalId",
                            value: "value",
                        },
                    ],
                    contactMethods: [
                        {
                            type: "email",
                            value: "value",
                        },
                        {
                            type: "email",
                            value: "value",
                        },
                    ],
                    relationship: {
                        isControlProng: true,
                    },
                },
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2023-01-15",
            address: { address1: "address1", city: "city", state: "state", country: "xy", postalCode: "postalCode" },
            identifiers: [
                { type: "nationalId", value: "value" },
                { type: "nationalId", value: "value" },
            ],
            contactMethods: [
                { type: "email", value: "value" },
                { type: "email", value: "value" },
            ],
            relationship: { isControlProng: true },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/owners/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.owners.update({
                ownerId: 1,
                body: {
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2023-01-15",
                    address: {
                        address1: "address1",
                        city: "city",
                        state: "state",
                        country: "xy",
                        postalCode: "postalCode",
                    },
                    identifiers: [
                        {
                            type: "nationalId",
                            value: "value",
                        },
                        {
                            type: "nationalId",
                            value: "value",
                        },
                    ],
                    contactMethods: [
                        {
                            type: "email",
                            value: "value",
                        },
                        {
                            type: "email",
                            value: "value",
                        },
                    ],
                    relationship: {
                        isControlProng: true,
                    },
                },
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2023-01-15",
            address: { address1: "address1", city: "city", state: "state", country: "xy", postalCode: "postalCode" },
            identifiers: [
                { type: "nationalId", value: "value" },
                { type: "nationalId", value: "value" },
            ],
            contactMethods: [
                { type: "email", value: "value" },
                { type: "email", value: "value" },
            ],
            relationship: { isControlProng: true },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .put("/owners/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.owners.update({
                ownerId: 1,
                body: {
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2023-01-15",
                    address: {
                        address1: "address1",
                        city: "city",
                        state: "state",
                        country: "xy",
                        postalCode: "postalCode",
                    },
                    identifiers: [
                        {
                            type: "nationalId",
                            value: "value",
                        },
                        {
                            type: "nationalId",
                            value: "value",
                        },
                    ],
                    contactMethods: [
                        {
                            type: "email",
                            value: "value",
                        },
                        {
                            type: "email",
                            value: "value",
                        },
                    ],
                    relationship: {
                        isControlProng: true,
                    },
                },
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2023-01-15",
            address: { address1: "address1", city: "city", state: "state", country: "xy", postalCode: "postalCode" },
            identifiers: [
                { type: "nationalId", value: "value" },
                { type: "nationalId", value: "value" },
            ],
            contactMethods: [
                { type: "email", value: "value" },
                { type: "email", value: "value" },
            ],
            relationship: { isControlProng: true },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .put("/owners/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.owners.update({
                ownerId: 1,
                body: {
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2023-01-15",
                    address: {
                        address1: "address1",
                        city: "city",
                        state: "state",
                        country: "xy",
                        postalCode: "postalCode",
                    },
                    identifiers: [
                        {
                            type: "nationalId",
                            value: "value",
                        },
                        {
                            type: "nationalId",
                            value: "value",
                        },
                    ],
                    contactMethods: [
                        {
                            type: "email",
                            value: "value",
                        },
                        {
                            type: "email",
                            value: "value",
                        },
                    ],
                    relationship: {
                        isControlProng: true,
                    },
                },
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            firstName: "firstName",
            lastName: "lastName",
            dateOfBirth: "2023-01-15",
            address: { address1: "address1", city: "city", state: "state", country: "xy", postalCode: "postalCode" },
            identifiers: [
                { type: "nationalId", value: "value" },
                { type: "nationalId", value: "value" },
            ],
            contactMethods: [
                { type: "email", value: "value" },
                { type: "email", value: "value" },
            ],
            relationship: { isControlProng: true },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .put("/owners/1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.owners.update({
                ownerId: 1,
                body: {
                    firstName: "firstName",
                    lastName: "lastName",
                    dateOfBirth: "2023-01-15",
                    address: {
                        address1: "address1",
                        city: "city",
                        state: "state",
                        country: "xy",
                        postalCode: "postalCode",
                    },
                    identifiers: [
                        {
                            type: "nationalId",
                            value: "value",
                        },
                        {
                            type: "nationalId",
                            value: "value",
                        },
                    ],
                    contactMethods: [
                        {
                            type: "email",
                            value: "value",
                        },
                        {
                            type: "email",
                            value: "value",
                        },
                    ],
                    relationship: {
                        isControlProng: true,
                    },
                },
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        server.mockEndpoint().delete("/owners/1").respondWith().statusCode(200).build();

        const response = await client.boarding.owners.delete({
            ownerId: 1,
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().delete("/owners/1").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.delete({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().delete("/owners/1").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.delete({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/owners/1").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.delete({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().delete("/owners/1").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.delete({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server.mockEndpoint().delete("/owners/1").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.boarding.owners.delete({
                ownerId: 1,
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });
});
