// This file was auto-generated by Fern from our API Definition.

import * as Payroc from "../../../src/api/index";
import { PayrocClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockBearer } from "../mockAuth";

describe("TerminalOrdersClient", () => {
    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            terminalOrderId: "12345",
            status: "open",
            trainingProvider: "payroc",
            shipping: {
                preferences: { method: "nextDay", saturdayDelivery: true },
                address: {
                    recipientName: "Recipient Name",
                    businessName: "Company Ltd",
                    addressLine1: "1 Example Ave.",
                    addressLine2: "Example Address Line 2",
                    city: "Chicago",
                    state: "Illinois",
                    postalCode: "60056",
                    email: "example@mail.com",
                    phone: "2025550164",
                },
            },
            orderItems: [
                {
                    links: [
                        {
                            processingTerminalId: "processingTerminalId",
                            link: {
                                href: "https://api.payroc.com/v1/processing-terminals/38765",
                                rel: "processingTerminal",
                                method: "get",
                            },
                        },
                    ],
                    type: "solution",
                    solutionTemplateId: "Roc Services_DX8000",
                    solutionQuantity: 1,
                    deviceCondition: "new",
                    solutionSetup: {
                        timezone: "America/Chicago",
                        industryTemplateId: "Retail",
                        gatewaySettings: {
                            merchantPortfolioId: "Company Ltd",
                            merchantTemplateId: "Company Ltd Merchant Template",
                            userTemplateId: "Company Ltd User Template",
                            terminalTemplateId: "Company Ltd Terminal Template",
                        },
                        applicationSettings: {
                            clerkPrompt: false,
                            security: { refundPassword: true, keyedSalePassword: false, reversalPassword: true },
                        },
                        deviceSettings: { numberOfMobileUsers: 2, communicationType: "wifi" },
                        batchClosure: { batchCloseType: "automatic", batchCloseTime: "23:40" },
                        receiptNotifications: { emailReceipt: true, smsReceipt: false },
                        taxes: [{ taxRate: 6, taxLabel: "Sales Tax" }],
                        tips: { enabled: false },
                        tokenization: true,
                    },
                },
            ],
            createdDate: "2020-09-08T12:00:00Z",
            lastModifiedDate: "2020-09-09T12:00:00Z",
        };
        server
            .mockEndpoint()
            .get("/terminal-orders/12345")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.boarding.terminalOrders.retrieve({
            terminalOrderId: "12345",
        });
        expect(response).toEqual({
            terminalOrderId: "12345",
            status: "open",
            trainingProvider: "payroc",
            shipping: {
                preferences: {
                    method: "nextDay",
                    saturdayDelivery: true,
                },
                address: {
                    recipientName: "Recipient Name",
                    businessName: "Company Ltd",
                    addressLine1: "1 Example Ave.",
                    addressLine2: "Example Address Line 2",
                    city: "Chicago",
                    state: "Illinois",
                    postalCode: "60056",
                    email: "example@mail.com",
                    phone: "2025550164",
                },
            },
            orderItems: [
                {
                    links: [
                        {
                            processingTerminalId: "processingTerminalId",
                            link: {
                                href: "https://api.payroc.com/v1/processing-terminals/38765",
                                rel: "processingTerminal",
                                method: "get",
                            },
                        },
                    ],
                    type: "solution",
                    solutionTemplateId: "Roc Services_DX8000",
                    solutionQuantity: 1,
                    deviceCondition: "new",
                    solutionSetup: {
                        timezone: "America/Chicago",
                        industryTemplateId: "Retail",
                        gatewaySettings: {
                            merchantPortfolioId: "Company Ltd",
                            merchantTemplateId: "Company Ltd Merchant Template",
                            userTemplateId: "Company Ltd User Template",
                            terminalTemplateId: "Company Ltd Terminal Template",
                        },
                        applicationSettings: {
                            clerkPrompt: false,
                            security: {
                                refundPassword: true,
                                keyedSalePassword: false,
                                reversalPassword: true,
                            },
                        },
                        deviceSettings: {
                            numberOfMobileUsers: 2,
                            communicationType: "wifi",
                        },
                        batchClosure: {
                            batchCloseType: "automatic",
                            batchCloseTime: "23:40",
                        },
                        receiptNotifications: {
                            emailReceipt: true,
                            smsReceipt: false,
                        },
                        taxes: [
                            {
                                taxRate: 6,
                                taxLabel: "Sales Tax",
                            },
                        ],
                        tips: {
                            enabled: false,
                        },
                        tokenization: true,
                    },
                },
            ],
            createdDate: "2020-09-08T12:00:00Z",
            lastModifiedDate: "2020-09-09T12:00:00Z",
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/terminal-orders/terminalOrderId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.terminalOrders.retrieve({
                terminalOrderId: "terminalOrderId",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/terminal-orders/terminalOrderId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.terminalOrders.retrieve({
                terminalOrderId: "terminalOrderId",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/terminal-orders/terminalOrderId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.terminalOrders.retrieve({
                terminalOrderId: "terminalOrderId",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/terminal-orders/terminalOrderId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.terminalOrders.retrieve({
                terminalOrderId: "terminalOrderId",
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/terminal-orders/terminalOrderId")
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.terminalOrders.retrieve({
                terminalOrderId: "terminalOrderId",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/terminal-orders/terminalOrderId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.boarding.terminalOrders.retrieve({
                terminalOrderId: "terminalOrderId",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });
});
