// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../index.js";

/**
 * Object that contains information about the customer's payment details.
 */
export type SubscriptionRequestPaymentMethod = Payroc.repeatPayments.SubscriptionRequestPaymentMethod.SecureToken;

export namespace SubscriptionRequestPaymentMethod {
    export interface SecureToken extends Payroc.SecureTokenPayload {
        type: "secureToken";
    }
}
