// This file was auto-generated by Fern from our API Definition.

import { ApplePaySessionsClient } from "./api/resources/applePaySessions/client/Client.js";
import { AttachmentsClient } from "./api/resources/attachments/client/Client.js";
import { AuthClient } from "./api/resources/auth/client/Client.js";
import { BankTransferPaymentsClient } from "./api/resources/bankTransferPayments/client/Client.js";
import { BoardingClient } from "./api/resources/boarding/client/Client.js";
import { CardPaymentsClient } from "./api/resources/cardPayments/client/Client.js";
import { FundingClient } from "./api/resources/funding/client/Client.js";
import { HostedFieldsClient } from "./api/resources/hostedFields/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { PaymentFeaturesClient } from "./api/resources/paymentFeatures/client/Client.js";
import { PaymentLinksClient } from "./api/resources/paymentLinks/client/Client.js";
import { PayrocCloudClient } from "./api/resources/payrocCloud/client/Client.js";
import { RepeatPaymentsClient } from "./api/resources/repeatPayments/client/Client.js";
import { ReportingClient } from "./api/resources/reporting/client/Client.js";
import { TokenizationClient } from "./api/resources/tokenization/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace PayrocClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PayrocClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PayrocClient.Options>;
    protected _paymentLinks: PaymentLinksClient | undefined;
    protected _hostedFields: HostedFieldsClient | undefined;
    protected _applePaySessions: ApplePaySessionsClient | undefined;
    protected _attachments: AttachmentsClient | undefined;
    protected _auth: AuthClient | undefined;
    protected _funding: FundingClient | undefined;
    protected _bankTransferPayments: BankTransferPaymentsClient | undefined;
    protected _boarding: BoardingClient | undefined;
    protected _cardPayments: CardPaymentsClient | undefined;
    protected _notifications: NotificationsClient | undefined;
    protected _paymentFeatures: PaymentFeaturesClient | undefined;
    protected _payrocCloud: PayrocCloudClient | undefined;
    protected _repeatPayments: RepeatPaymentsClient | undefined;
    protected _reporting: ReportingClient | undefined;
    protected _tokenization: TokenizationClient | undefined;

    constructor(options: PayrocClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get paymentLinks(): PaymentLinksClient {
        return (this._paymentLinks ??= new PaymentLinksClient(this._options));
    }

    public get hostedFields(): HostedFieldsClient {
        return (this._hostedFields ??= new HostedFieldsClient(this._options));
    }

    public get applePaySessions(): ApplePaySessionsClient {
        return (this._applePaySessions ??= new ApplePaySessionsClient(this._options));
    }

    public get attachments(): AttachmentsClient {
        return (this._attachments ??= new AttachmentsClient(this._options));
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get funding(): FundingClient {
        return (this._funding ??= new FundingClient(this._options));
    }

    public get bankTransferPayments(): BankTransferPaymentsClient {
        return (this._bankTransferPayments ??= new BankTransferPaymentsClient(this._options));
    }

    public get boarding(): BoardingClient {
        return (this._boarding ??= new BoardingClient(this._options));
    }

    public get cardPayments(): CardPaymentsClient {
        return (this._cardPayments ??= new CardPaymentsClient(this._options));
    }

    public get notifications(): NotificationsClient {
        return (this._notifications ??= new NotificationsClient(this._options));
    }

    public get paymentFeatures(): PaymentFeaturesClient {
        return (this._paymentFeatures ??= new PaymentFeaturesClient(this._options));
    }

    public get payrocCloud(): PayrocCloudClient {
        return (this._payrocCloud ??= new PayrocCloudClient(this._options));
    }

    public get repeatPayments(): RepeatPaymentsClient {
        return (this._repeatPayments ??= new RepeatPaymentsClient(this._options));
    }

    public get reporting(): ReportingClient {
        return (this._reporting ??= new ReportingClient(this._options));
    }

    public get tokenization(): TokenizationClient {
        return (this._tokenization ??= new TokenizationClient(this._options));
    }
}
