// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { PaymentsClient } from "../resources/payments/client/Client.js";
import { RefundsClient } from "../resources/refunds/client/Client.js";

export declare namespace CardPaymentsClient {
    export type Options = BaseClientOptions;
}

export class CardPaymentsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CardPaymentsClient.Options>;
    protected _payments: PaymentsClient | undefined;
    protected _refunds: RefundsClient | undefined;

    constructor(options: CardPaymentsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get payments(): PaymentsClient {
        return (this._payments ??= new PaymentsClient(this._options));
    }

    public get refunds(): RefundsClient {
        return (this._refunds ??= new RefundsClient(this._options));
    }
}
