// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
 *         processingTerminalId: "1234001",
 *         channel: "web",
 *         operator: "Jane",
 *         source: {
 *             type: "card",
 *             cardDetails: {
 *                 entryMethod: "raw",
 *                 device: {
 *                     model: "bbposChp",
 *                     serialNumber: "1850010868"
 *                 },
 *                 rawData: "A1B2C3D4E5F67890ABCD1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF"
 *             }
 *         }
 *     }
 */
export interface SingleUseTokenRequest {
    /** Unique identifier that our gateway assigned to the terminal. */
    processingTerminalId: string;
    /** Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency). */
    "Idempotency-Key": string;
    /** Channel that the merchant used to receive the payment details. */
    channel: SingleUseTokenRequest.Channel;
    /** Operator who initiated the request. */
    operator?: string;
    /**
     * Polymorphic object that contains the payment method to tokenize.
     *
     * The value of the type parameter determines which variant you should use:
     * -	`ach` - Automated Clearing House (ACH) details
     * -	`pad` - Pre-authorized debit (PAD) details
     * -	`card` - Payment card details
     */
    source: Payroc.tokenization.SingleUseTokenRequestSource;
}

export namespace SingleUseTokenRequest {
    /** Channel that the merchant used to receive the payment details. */
    export const Channel = {
        Pos: "pos",
        Web: "web",
        Moto: "moto",
    } as const;
    export type Channel = (typeof Channel)[keyof typeof Channel];
}
