// This file was auto-generated by Fern from our API Definition.

import * as Payroc from "../../../src/api/index";
import { PayrocClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockBearer } from "../mockAuth";

describe("RefundsClient", () => {
    test("reversePayment (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            paymentId: "M2MJOG6O2Y",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Large Pepperoni Pizza",
                amount: 4999,
                currency: "USD",
                breakdown: {
                    subtotal: 4347,
                    tip: { type: "percentage", amount: 500, percentage: 10 },
                    taxes: [{ name: "VAT", rate: 5, amount: 217 }],
                },
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "pad",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "1234567890",
                transitNumber: "76543",
                institutionNumber: "543",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            refunds: [
                {
                    refundId: "CD3HN88U9F",
                    dateTime: "2024-07-14T12:25:00Z",
                    currency: "AED",
                    amount: 4999,
                    status: "ready",
                    responseCode: "A",
                    responseMessage: "Transaction refunded",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            ],
            returns: [
                {
                    paymentId: "M2MJOG6O2Y",
                    date: "2024-07-02",
                    returnCode: "R11",
                    returnReason: "Customer advises not authorized",
                    represented: false,
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            ],
            representment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "payment",
                status: "reversal",
                authorizedAmount: 4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "Payment Approved",
                processorResponseCode: "A",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/M2MJOG6O2Y/reverse")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.bankTransferPayments.refunds.reversePayment({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            paymentId: "M2MJOG6O2Y",
        });
        expect(response).toEqual({
            paymentId: "M2MJOG6O2Y",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Large Pepperoni Pizza",
                amount: 4999,
                currency: "USD",
                breakdown: {
                    subtotal: 4347,
                    tip: {
                        type: "percentage",
                        amount: 500,
                        percentage: 10,
                    },
                    taxes: [
                        {
                            name: "VAT",
                            rate: 5,
                            amount: 217,
                        },
                    ],
                },
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "pad",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "1234567890",
                transitNumber: "76543",
                institutionNumber: "543",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            refunds: [
                {
                    refundId: "CD3HN88U9F",
                    dateTime: "2024-07-14T12:25:00Z",
                    currency: "AED",
                    amount: 4999,
                    status: "ready",
                    responseCode: "A",
                    responseMessage: "Transaction refunded",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            ],
            returns: [
                {
                    paymentId: "M2MJOG6O2Y",
                    date: "2024-07-02",
                    returnCode: "R11",
                    returnReason: "Customer advises not authorized",
                    represented: false,
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            ],
            representment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "payment",
                status: "reversal",
                authorizedAmount: 4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "Payment Approved",
                processorResponseCode: "A",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("reversePayment (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("reversePayment (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("reversePayment (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("reversePayment (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("reversePayment (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("reversePayment (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("reversePayment (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("reversePayment (9)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reversePayment({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("refund (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 4999, description: "amount to refund" };
        const rawResponseBody = {
            paymentId: "M2MJOG6O2Y",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
                breakdown: {
                    subtotal: 4347,
                    tip: { type: "percentage", amount: 435, percentage: 10 },
                    taxes: [{ name: "Sales Tax", rate: 5, amount: 217 }],
                },
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "pad",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "1234567890",
                transitNumber: "76543",
                institutionNumber: "543",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            refunds: [
                {
                    refundId: "CD3HN88U9F",
                    dateTime: "2024-07-14T12:25:00Z",
                    currency: "AED",
                    amount: 4999,
                    status: "ready",
                    responseCode: "A",
                    responseMessage: "Transaction refunded",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            ],
            returns: [
                {
                    paymentId: "M2MJOG6O2Y",
                    date: "2024-07-02",
                    returnCode: "R11",
                    returnReason: "Customer advises not authorized",
                    represented: false,
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            ],
            representment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "payment",
                status: "reversal",
                authorizedAmount: 4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "Payment Approved",
                processorResponseCode: "A",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/M2MJOG6O2Y/refund")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.bankTransferPayments.refunds.refund({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            paymentId: "M2MJOG6O2Y",
            amount: 4999,
            description: "amount to refund",
        });
        expect(response).toEqual({
            paymentId: "M2MJOG6O2Y",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
                breakdown: {
                    subtotal: 4347,
                    tip: {
                        type: "percentage",
                        amount: 435,
                        percentage: 10,
                    },
                    taxes: [
                        {
                            name: "Sales Tax",
                            rate: 5,
                            amount: 217,
                        },
                    ],
                },
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "pad",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "1234567890",
                transitNumber: "76543",
                institutionNumber: "543",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            refunds: [
                {
                    refundId: "CD3HN88U9F",
                    dateTime: "2024-07-14T12:25:00Z",
                    currency: "AED",
                    amount: 4999,
                    status: "ready",
                    responseCode: "A",
                    responseMessage: "Transaction refunded",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            ],
            returns: [
                {
                    paymentId: "M2MJOG6O2Y",
                    date: "2024-07-02",
                    returnCode: "R11",
                    returnReason: "Customer advises not authorized",
                    represented: false,
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            ],
            representment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "payment",
                status: "reversal",
                authorizedAmount: 4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "Payment Approved",
                processorResponseCode: "A",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("refund (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("refund (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("refund (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("refund (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("refund (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("refund (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("refund (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("refund (9)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = { amount: 1000000, description: "x" };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-payments/paymentId/refund")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.refund({
                "Idempotency-Key": "idempotencyKey",
                paymentId: "paymentId",
                amount: 1000000,
                description: "x",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            refundMethod: {
                type: "ach",
                nameOnAccount: "Shara Hazel Hopper",
                accountNumber: "1234567890",
                routingNumber: "123456789",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        const rawResponseBody = {
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.bankTransferPayments.refunds.create({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            refundMethod: {
                type: "ach",
                nameOnAccount: "Shara Hazel Hopper",
                accountNumber: "1234567890",
                routingNumber: "123456789",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
        expect(response).toEqual({
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });
        const rawRequestBody = {
            processingTerminalId: "buzz",
            order: {},
            refundMethod: { type: "ach", nameOnAccount: "x", accountNumber: "buzz", routingNumber: "nectarine" },
        };
        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.create({
                "Idempotency-Key": "idempotencyKey",
                processingTerminalId: "buzz",
                order: {},
                refundMethod: {
                    type: "ach",
                    nameOnAccount: "x",
                    accountNumber: "buzz",
                    routingNumber: "nectarine",
                },
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/CD3HN88U9F")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.bankTransferPayments.refunds.retrieve({
            refundId: "CD3HN88U9F",
        });
        expect(response).toEqual({
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "ready",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .get("/bank-transfer-refunds/refundId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.retrieve({
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });

    test("reverseRefund (1)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = {
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [{ type: "email", value: "jane.doe@example.com" }],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: { rel: "previous", method: "get", href: "<uri>" },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: { rel: "previous", method: "get", href: "<uri>" },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "reversal",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [{ name: "yourCustomField", value: "abc123" }],
        };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/CD3HN88U9F/reverse")
            .header("Idempotency-Key", "8e03978e-40d5-43e8-bc93-6894a57f9324")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.bankTransferPayments.refunds.reverseRefund({
            "Idempotency-Key": "8e03978e-40d5-43e8-bc93-6894a57f9324",
            refundId: "CD3HN88U9F",
        });
        expect(response).toEqual({
            refundId: "CD3HN88U9F",
            processingTerminalId: "1234001",
            order: {
                orderId: "OrderRef6543",
                dateTime: "2024-07-02T15:30:00Z",
                description: "Refund for order OrderRef6543",
                amount: 4999,
                currency: "USD",
            },
            customer: {
                notificationLanguage: "en",
                contactMethods: [
                    {
                        type: "email",
                        value: "jane.doe@example.com",
                    },
                ],
            },
            bankAccount: {
                type: "ach",
                secCode: "web",
                nameOnAccount: "Sarah Hazel Hopper",
                accountNumber: "123456789",
                routingNumber: "123456789",
                secureToken: {
                    secureTokenId: "MREF_abc1de23-f4a5-6789-bcd0-12e345678901fa",
                    customerName: "Sarah Hazel Hopper",
                    token: "296753123456",
                    status: "notValidated",
                    link: {
                        rel: "previous",
                        method: "get",
                        href: "<uri>",
                    },
                },
            },
            payment: {
                paymentId: "M2MJOG6O2Y",
                dateTime: "2024-07-02T15:30:00Z",
                currency: "AED",
                amount: 4999,
                status: "ready",
                responseCode: "A",
                responseMessage: "Transaction approved",
                link: {
                    rel: "previous",
                    method: "get",
                    href: "<uri>",
                },
            },
            transactionResult: {
                type: "unreferencedRefund",
                status: "reversal",
                authorizedAmount: -4999,
                currency: "USD",
                responseCode: "A",
                responseMessage: "NoError",
                processorResponseCode: "0",
            },
            customFields: [
                {
                    name: "yourCustomField",
                    value: "abc123",
                },
            ],
        });
    });

    test("reverseRefund (2)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.BadRequestError);
    });

    test("reverseRefund (3)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.UnauthorizedError);
    });

    test("reverseRefund (4)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.ForbiddenError);
    });

    test("reverseRefund (5)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotFoundError);
    });

    test("reverseRefund (6)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(406)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.NotAcceptableError);
    });

    test("reverseRefund (7)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.ConflictError);
    });

    test("reverseRefund (8)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(415)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.UnsupportedMediaTypeError);
    });

    test("reverseRefund (9)", async () => {
        const server = mockServerPool.createServer();
        mockBearer(server);

        const client = new PayrocClient({
            maxRetries: 0,
            apiKey: "x-api-key",
            environment: { api: server.baseUrl, identity: server.baseUrl },
        });

        const rawResponseBody = { type: "type", title: "title", status: 1, detail: "detail" };
        server
            .mockEndpoint()
            .post("/bank-transfer-refunds/refundId/reverse")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.bankTransferPayments.refunds.reverseRefund({
                "Idempotency-Key": "idempotencyKey",
                refundId: "refundId",
            });
        }).rejects.toThrow(Payroc.InternalServerError);
    });
});
