// This file was auto-generated by Fern from our API Definition.

export const ListPaymentsRequestTipModeItem = {
    NoTip: "noTip",
    Prompted: "prompted",
    Adjusted: "adjusted",
} as const;
export type ListPaymentsRequestTipModeItem =
    (typeof ListPaymentsRequestTipModeItem)[keyof typeof ListPaymentsRequestTipModeItem];
