// This file was auto-generated by Fern from our API Definition.

import type * as Payroc from "../../../../../../index.js";

/**
 * @example
 *     {
 *         status: "registered",
 *         event: "processingAccount.status.changed"
 *     }
 */
export interface ListEventSubscriptionsRequest {
    /** Filter event subscriptions by subscription status. */
    status?: Payroc.notifications.ListEventSubscriptionsRequestStatus;
    /** Filter event subscriptions by an event type. For a list of event types, go to [Events List](https://docs.payroc.com/knowledge/events/events-list). */
    event?: string;
}
